import type { Track } from "@/engine";

/**
 * The playlist. This file *is* the product — the engineering was the easy half.
 *
 * **Where these came from.** One place: the YouTube search
 * `https://www.youtube.com/results?search_query=bus+hits+malayalam`, and every
 * playlist that search surfaces. `.harvest/ytsearch.sh` dumps that pool (~1,350
 * rows, ~870 distinct single-song uploads) and `npm run mine-search` turns it into
 * ranked candidates by reading each upload's own metadata — 710 inspected so far,
 * 149 of them worth keeping. What it has to throw away is most of the job:
 *
 *  · **jukeboxes** — over a third of that search is 20-to-60-minute "non-stop bus
 *    playlist" uploads. Real listening, useless as tracks: one entry, no per-song
 *    metadata, no seek that means anything.
 *  · **not-Malayalam** — the playlists that search surfaces drift, so Tamil and
 *    Hindi come with them. A script test is not enough, because a Tamil upload's
 *    title is Latin: "Mersal", "Bigil" and "Vettaikaaran" all sailed through one.
 *  · **not-the-song** — remixes, DJ edits, covers, karaoke, status clips.
 *  · **metadata-less** — an upload that cannot yield a film and a singer is not a
 *    track this playlist can honestly carry.
 *
 * **The years are mine, not the uploads'.** Almost every description reports the
 * upload or copyright year — a 2005 song "from 2023" — so the year here is the
 * film's, and where a film's year is not something that can be stated plainly the
 * track carries none rather than a confident invention. Same for the two album
 * tracks at the bottom, which no public source dates.
 *
 * **Every ID is a label, studio or artist-channel upload wherever one exists**,
 * because those are the ones that stay up and stay embeddable. `npm run
 * check-tracks` proves each still resolves. Malayalam titles are typed by hand,
 * taking the official spelling from the upload title wherever it carried one.
 *
 * The list is grouped by decade and ordered by the film's year, so the shape of the
 * playlist is legible at a glance rather than being an argument about ordering.
 *
 * To suggest a song: it has to be in that search's pool. Re-run the harvest and the
 * miner — it caches per video, so a re-run only asks about what it has never seen —
 * then open a pull request against this file.
 */
export const tracks: readonly Track[] = [
  /* ── the 80s: the songs that never stopped playing on these routes ────── */
  {
    youtubeId: "2mq7tut9cCU",
    title: "Vaakapoo Maram",
    titleMl: "വാകപ്പൂമരം",
    movie: "Anubhavam",
    year: 1976,
    singer: "K. J. Yesudas",
    vibe: "melody",
  },
  {
    youtubeId: "_xmjbcFz_MM",
    title: "Ushakiranangal Pulki",
    titleMl: "ഉഷാ കിരണങ്ങൾ പുൽകി",
    movie: "Guruvayoor Kesavan",
    year: 1977,
    singer: "K. J. Yesudas",
    vibe: "melody",
  },
  {
    youtubeId: "UCt6mp5Nnx4",
    title: "Mizhiyoram Nananju",
    titleMl: "മിഴിയോരം നനഞ്ഞൊഴുകും",
    movie: "Manjil Virinja Pookkal",
    year: 1980,
    composer: "Jerry Amaldev",
    singer: "K. J. Yesudas",
    vibe: "melody",
  },
  {
    youtubeId: "WrRUrCwVoPQ",
    title: "Thumbi Vaa",
    titleMl: "തുമ്പീ വാ",
    movie: "Olangal",
    year: 1982,
    composer: "Ilaiyaraaja",
    singer: "S. Janaki",
    vibe: "melody",
  },
  {
    youtubeId: "nKhh3aqNRWA",
    title: "Aayiram Kannumai",
    titleMl: "ആയിരം കണ്ണുമായ്",
    movie: "Nokkethadhoorathu Kannum Nattu",
    year: 1984,
    composer: "Jerry Amaldev",
    singer: "K. S. Chithra",
    vibe: "melody",
  },
  {
    youtubeId: "HTNDApRIv-M",
    title: "Kasthoorimaan Kurunne",
    titleMl: "കസ്തൂരിമാൻ കുരുന്നേ",
    movie: "Kanamarayathu",
    year: 1984,
    composer: "Shyam",
    singer: "S. Janaki",
    vibe: "melody",
  },
  {
    youtubeId: "Wt-xeSyN_1U",
    title: "Oru Madhurakkinavin",
    titleMl: "ഒരു മധുരക്കിനാവിൻ",
    movie: "Kanamarayathu",
    year: 1984,
    composer: "Shyam",
    singer: "K. J. Yesudas",
    vibe: "melody",
  },
  {
    youtubeId: "emF9R6LGb7A",
    title: "Anuragini Itha",
    titleMl: "അനുരാഗിണീ ഇതാ",
    movie: "Oru Kudakkeezhil",
    year: 1985,
    composer: "Johnson",
    singer: "K. J. Yesudas",
    vibe: "melody",
  },
  {
    youtubeId: "i3Pp2fLmxJU",
    title: "Bhoomippennin Poomey",
    titleMl: "ഭൂമിപ്പെണ്ണിൻ പൂമെയ് മൂടും",
    movie: "Oru Kudakkeezhil",
    year: 1985,
    composer: "Shyam",
    vibe: "melody",
  },
  {
    youtubeId: "gzkBVmxxDY8",
    title: "Devadoothar Paadi",
    titleMl: "ദേവദൂതർ പാടി",
    movie: "Kaathodu Kaathoram",
    year: 1985,
    composer: "Ouseppachan",
    singer: "K. J. Yesudas",
    vibe: "melody",
  },
  {
    youtubeId: "iPa1C30GzWE",
    title: "Ilam Manjin Kulirumay",
    titleMl: "ഇളം മഞ്ഞിൻ കുളിരുമായ്",
    movie: "Ninnishtam Ennishtam",
    year: 1986,
    composer: "Kannur Rajan",
    singer: "K. J. Yesudas & S. Janaki",
    vibe: "melody",
  },
  {
    youtubeId: "YqEhznI1xak",
    title: "Koottil Ninnum",
    titleMl: "കൂട്ടിൽ നിന്നും",
    movie: "Thalavattam",
    year: 1986,
    composer: "Raghu Kumar",
    singer: "K. J. Yesudas",
    vibe: "melody",
  },
  {
    youtubeId: "IgcgMXFszyg",
    title: "Poonkaatte Poyi Chollamo",
    titleMl: "പൂങ്കാറ്റേ പോയി ചൊല്ലാമോ",
    movie: "Shyama",
    year: 1986,
    composer: "Raghukumar",
    singer: "Unni Menon & K. S. Chithra",
    vibe: "melody",
  },
  {
    youtubeId: "1VcC6msGcCA",
    title: "Sreelathikakal",
    titleMl: "ശ്രീലതികകൾ",
    movie: "Sukhamo Devi",
    year: 1986,
    composer: "Raveendran",
    singer: "K. J. Yesudas",
    vibe: "melody",
  },
  {
    youtubeId: "pBbHUxjiKd8",
    title: "Onnam Ragam Paadi",
    titleMl: "ഒന്നാം രാഗം പാടി",
    movie: "Thoovanathumbikal",
    year: 1987,
    composer: "Perumbavoor G. Raveendranath",
    singer: "G. Venugopal & K. S. Chithra",
    vibe: "melody",
  },
  {
    youtubeId: "VnOLG5amCIQ",
    title: "Unnikale Oru Kadha Parayam",
    titleMl: "ഉണ്ണികളേ ഒരു കഥ പറയാം",
    movie: "Unnikale Oru Kadha Parayam",
    year: 1987,
    composer: "Ouseppachan",
    singer: "K. J. Yesudas",
    vibe: "melody",
  },
  {
    youtubeId: "JGr_ooHcKpQ",
    title: "Olichirikkan",
    titleMl: "ഒളിച്ചിരിക്കാൻ",
    movie: "Aranyakam",
    year: 1988,
    composer: "Bombay Ravi",
    singer: "K. S. Chithra",
    vibe: "melody",
  },
  {
    youtubeId: "gySAG8IUQak",
    title: "Thamarakkili Paadunnu",
    titleMl: "താമരക്കിളി പാടുന്നു",
    movie: "Moonnam Pakkam",
    year: 1988,
    composer: "Johnson",
    singer: "K. S. Chithra",
    vibe: "melody",
  },
  {
    youtubeId: "b3tFr27Ht5M",
    title: "Kanneerpoovinte Kavilil",
    titleMl: "കണ്ണീർപ്പൂവിന്റെ കവിളിൽ",
    movie: "Kireedam",
    year: 1989,
    composer: "Johnson",
    singer: "K. J. Yesudas",
    vibe: "melody",
  },

  /* ── the 90s ──────────────────────────────────────────────────────────── */
  {
    youtubeId: "GtFLoz-b9cQ",
    title: "Gopika Vasantham",
    titleMl: "ഗോപിക വസന്തം",
    movie: "His Highness Abdulla",
    year: 1990,
    composer: "Raveendran",
    singer: "K. J. Yesudas",
    vibe: "melody",
  },
  {
    youtubeId: "mUJ_S72T-q8",
    title: "Pramadavanam Veendum",
    titleMl: "പ്രമദവനം വീണ്ടും",
    movie: "His Highness Abdulla",
    year: 1990,
    composer: "Raveendran",
    singer: "K. J. Yesudas",
    vibe: "melody",
  },
  {
    youtubeId: "b5gNID-T5m4",
    title: "Thu Badi Masha Allah",
    titleMl: "തൂ ബഡി മാഷാ അള്ളാ",
    movie: "His Highness Abdulla",
    year: 1990,
    composer: "Raveendran",
    singer: "M. G. Sreekumar",
    vibe: "mass",
  },
  {
    youtubeId: "G3UefvEW6JU",
    title: "Anthiveyil Ponnu Thirum",
    titleMl: "അന്തിവെയിൽ പൊന്നുതിരും",
    movie: "Ulladakkam",
    year: 1991,
    composer: "Ouseppachan",
    singer: "K. J. Yesudas & Sujatha Mohan",
    vibe: "melody",
  },
  {
    youtubeId: "TPkCqQgwcHE",
    title: "Athira Varavayi",
    titleMl: "അതിര വരവായി",
    movie: "Thudarkadha",
    year: 1991,
    composer: "S. P. Venkatesh",
    singer: "K. S. Chithra & M. G. Sreekumar",
    vibe: "melody",
  },
  {
    youtubeId: "ibGZ1Q2MDaI",
    title: "Etho Varmukilin",
    titleMl: "ഏതോ വാർമുകിലിൻ",
    movie: "Pookkalam Varavayi",
    year: 1991,
    composer: "Ouseppachan",
    singer: "K. S. Chithra",
    vibe: "melody",
  },
  {
    youtubeId: "X9nrJGZOH7c",
    title: "Gopangane Aathmavile",
    titleMl: "ഗോപാങ്കനെ ആത്മാവിലെ",
    movie: "Bharatham",
    year: 1991,
    composer: "Raveendran",
    singer: "K. J. Yesudas",
    vibe: "melody",
  },
  {
    youtubeId: "cWlT6deMZJ8",
    title: "Kilukil Pambaram",
    titleMl: "കിലുകിൽ പമ്പരം",
    movie: "Kilukkam",
    year: 1991,
    composer: "S. P. Venkatesh",
    singer: "M. G. Sreekumar",
    vibe: "mass",
  },
  {
    youtubeId: "PJsrByKopEU",
    title: "Ramakadha Ganalayam",
    titleMl: "രാമകഥാ ഗാനലയം",
    movie: "Bharatham",
    year: 1991,
    composer: "Raveendran",
    singer: "K. J. Yesudas",
    vibe: "melody",
  },
  {
    youtubeId: "eD2PhS9aszI",
    title: "Sree Vinayakam",
    titleMl: "ശ്രീ വിനായകം",
    movie: "Bharatham",
    year: 1991,
    composer: "Raveendran",
    singer: "K. J. Yesudas",
    vibe: "melody",
  },
  {
    youtubeId: "YkuzkLZF_Rg",
    title: "Kaaveri Padamini",
    titleMl: "കാവേരി പാടമിനി",
    movie: "Raajashilpi",
    year: 1992,
    vibe: "mass",
  },
  {
    youtubeId: "2SoIDvKmDUM",
    title: "Kanakanilave Thuyilunaru",
    titleMl: "കനകനിലാവേ തുയിലുണരൂ",
    movie: "Kauravar",
    year: 1992,
    vibe: "melody",
  },
  {
    youtubeId: "gMtK5D5AWBg",
    title: "Padakali Chandi",
    titleMl: "പടകാളി ചണ്ഡി ചങ്കുരുത്തി",
    movie: "Yodha",
    year: 1992,
    composer: "A. R. Rahman",
    singer: "K. J. Yesudas & M. G. Sreekumar",
    vibe: "mass",
  },
  {
    youtubeId: "scyRSHpEtOI",
    title: "Pathiravayi Neram",
    titleMl: "പാതിരാവായി നേരം",
    movie: "Vietnam Colony",
    year: 1992,
    composer: "S. P. Venkatesh",
    singer: "K. J. Yesudas & K. S. Chithra",
    vibe: "melody",
  },
  {
    youtubeId: "9lBI1C8w8dI",
    title: "Premodaaranaay",
    titleMl: "പ്രേമോദാരനായ്",
    movie: "Kamaladalam",
    year: 1992,
    composer: "Raveendran",
    singer: "K. J. Yesudas",
    vibe: "melody",
  },
  {
    youtubeId: "qGiBuYygruI",
    title: "Saayanthanam Chandrika",
    titleMl: "സായന്തനം ചന്ദ്രികാ",
    movie: "Kamaladalam",
    year: 1992,
    composer: "Raveendran",
    singer: "K. J. Yesudas",
    vibe: "melody",
  },
  {
    youtubeId: "Iwywfokjovg",
    title: "Shanthamee Raathriyil",
    titleMl: "ശാന്തമീ രാത്രിയിൽ",
    movie: "Johnnie Walker",
    year: 1992,
    composer: "S. P. Venkatesh",
    singer: "M. G. Sreekumar",
    vibe: "melody",
  },
  {
    youtubeId: "LP45xF2gBxk",
    title: "Manju Manjeera",
    titleMl: "മഞ്ജു മഞ്ജീര",
    movie: "Aagneyam",
    year: 1993,
    composer: "Johnson",
    singer: "K. J. Yesudas",
    vibe: "melody",
  },
  {
    youtubeId: "_yuEu-naAa0",
    title: "Oru Murai Vanthu Paarthaya",
    titleMl: "ഒരു മുറൈ വന്തു പാർത്തായാ",
    movie: "Manichitrathazhu",
    year: 1993,
    composer: "M. G. Radhakrishnan",
    singer: "K. J. Yesudas",
    vibe: "melody",
  },
  {
    youtubeId: "ddJN4eyx1pI",
    title: "Varuvanillarumee",
    titleMl: "വരുവാനില്ലാരുമി",
    movie: "Manichitrathazhu",
    year: 1993,
    composer: "M. G. Radhakrishnan",
    singer: "K. S. Chithra",
    vibe: "melody",
  },
  {
    youtubeId: "w5bEVfXaw6M",
    title: "Avani Poovin",
    titleMl: "ആവണി പൂവിൻ",
    movie: "CID Unnikrishnan B.A. B.Ed",
    year: 1994,
    singer: "P. Jayachandran",
    vibe: "melody",
  },
  {
    youtubeId: "hk9FOM-_1YA",
    title: "Karutha Penne",
    titleMl: "കറുത്ത പെണ്ണേ",
    movie: "Thenmavin Kombathu",
    year: 1994,
    composer: "Berny–Ignatius",
    singer: "M. G. Sreekumar & K. S. Chithra",
    vibe: "mass",
  },
  {
    youtubeId: "5xvGA3DCtB0",
    title: "Enthinu Veroru Sooryodayam",
    titleMl: "എന്തിനു വേറൊരു സൂര്യോദയം",
    movie: "Mazhayethum Munpe",
    year: 1995,
    composer: "Raveendran",
    singer: "K. J. Yesudas & K. S. Chithra",
    vibe: "melody",
  },
  {
    youtubeId: "vp24h6mbb_8",
    title: "Ammoommakkili",
    titleMl: "അമ്മൂമ്മക്കിളി",
    movie: "Chandralekha",
    year: 1997,
    composer: "Berny–Ignatius",
    singer: "K. S. Chithra",
    vibe: "melody",
  },
  {
    youtubeId: "gKRyexzWW5w",
    title: "Appukutta Thoppikkara",
    titleMl: "അപ്പുക്കുട്ടാ തൊപ്പിക്കാര",
    movie: "Chandralekha",
    year: 1997,
    composer: "Berny–Ignatius",
    vibe: "mass",
  },
  {
    youtubeId: "EZI1nw1d55g",
    title: "Harimuraleeravam",
    titleMl: "ഹരിമുരളീരവം",
    movie: "Aaraam Thampuran",
    year: 1997,
    composer: "Raveendran",
    singer: "K. J. Yesudas",
    vibe: "melody",
  },
  {
    youtubeId: "lAppUVClf0w",
    title: "Maanathe Chandiranothoru",
    titleMl: "മാനത്തെ ചന്ദിരനൊത്തൊരു",
    movie: "Chandralekha",
    year: 1997,
    composer: "Berny–Ignatius",
    singer: "M. G. Sreekumar",
    vibe: "mass",
  },
  {
    youtubeId: "OVoPnym73jg",
    title: "Thamarapoovil",
    titleMl: "താമരപ്പൂവിൽ",
    movie: "Chandralekha",
    year: 1997,
    composer: "Berny–Ignatius",
    singer: "M. G. Sreekumar",
    vibe: "melody",
  },
  {
    youtubeId: "TKHenjnkPnw",
    title: "Aavani Ponnoonjaal",
    titleMl: "ആവണി പൊന്നൂഞ്ഞാൽ",
    movie: "Kottaram Veettile Appoottan",
    year: 1998,
    composer: "Berny–Ignatius",
    singer: "M. G. Sreekumar",
    vibe: "mass",
  },
  {
    youtubeId: "rbYmz_JR-kc",
    title: "Choolamadichu Karangi Nadakkum",
    titleMl: "ചൂളമടിച്ചു കറങ്ങി നടക്കും",
    movie: "Summer in Bethlehem",
    year: 1998,
    composer: "Vidyasagar",
    singer: "K. S. Chithra",
    vibe: "mass",
  },
  {
    youtubeId: "g--dmRDzFIg",
    title: "Confusion Theerkkaname",
    titleMl: "കൺഫ്യൂഷൻ തീർക്കണമേ",
    movie: "Summer in Bethlehem",
    year: 1998,
    composer: "Vidyasagar",
    singer: "M. G. Sreekumar",
    vibe: "mass",
  },
  {
    youtubeId: "fWeg0P36xcc",
    title: "Onnanam Kunninmel",
    titleMl: "ഒന്നാനാം കുന്നിന്മേൽ",
    movie: "Mayilppeelikkaavu",
    year: 1998,
    composer: "Berny–Ignatius",
    singer: "K. J. Yesudas & K. S. Chithra",
    vibe: "nadan",
  },
  {
    youtubeId: "bwzxaNKVjBQ",
    title: "Onnanam Kunninmel",
    titleMl: "ഒന്നാനാം കുന്നിന്മേൽ",
    movie: "Mayilppeelikkavu",
    year: 1998,
    composer: "Berny–Ignatius",
    singer: "K. J. Yesudas & K. S. Chithra",
    vibe: "nadan",
  },
  {
    youtubeId: "rWYdOVF4B74",
    title: "Palkudangal",
    titleMl: "പാൽക്കുടങ്ങൾ",
    movie: "Pranaya Nilavu",
    year: 1998,
    composer: "Vidyasagar",
    singer: "K. J. Yesudas",
    vibe: "melody",
  },
  {
    youtubeId: "n4w1vRKw580",
    title: "Sundariye",
    titleMl: "സുന്ദരിയേ",
    movie: "Oru Maravathoor Kanavu",
    year: 1998,
    composer: "Vidyasagar",
    singer: "K. J. Yesudas",
    vibe: "melody",
  },
  {
    youtubeId: "r3Uoeqat01c",
    title: "Ente Ulludukkum Kotti",
    titleMl: "എന്റെ ഉള്ളുടുക്കും കൊട്ടി",
    movie: "Deepasthambham Mahaashcharyam",
    year: 1999,
    composer: "Mohan Sithara",
    singer: "K. J. Yesudas & Radhika Thilak",
    vibe: "mass",
  },
  {
    youtubeId: "TtwrONQlc-k",
    title: "Margazhiye Mallikaye",
    titleMl: "മാർഗഴിയേ മല്ലികയേ",
    movie: "Megham",
    year: 1999,
    composer: "Ouseppachan",
    singer: "M. G. Sreekumar & Srinivas",
    vibe: "mass",
  },
  {
    youtubeId: "sbu-xxIGC7Y",
    title: "Nadodi Poothinkal",
    titleMl: "നാടോടി പൂന്തിങ്കൾ",
    movie: "Usthaad",
    year: 1999,
    composer: "Vidyasagar",
    singer: "M. G. Sreekumar & Sujatha Mohan",
    vibe: "melody",
  },
  {
    youtubeId: "IY-CmxAzgts",
    title: "Nandalala",
    titleMl: "നന്ദലാലാ",
    movie: "Independence",
    year: 1999,
    composer: "Suresh Peters",
    singer: "Swarnalatha",
    vibe: "mass",
  },
  {
    youtubeId: "ytwWpCuE5Ss",
    title: "Ninte Kannil Virunnu Vannu",
    titleMl: "നിന്റെ കണ്ണിൽ വിരുന്നു വന്നു",
    movie: "Deepasthambham Mahaashcharyam",
    year: 1999,
    composer: "Mohan Sithara",
    singer: "K. J. Yesudas",
    vibe: "melody",
  },

  /* ── the 2000s: the decade the back seat owned ────────────────────────── */
  {
    youtubeId: "6uEFZchRTqM",
    title: "Avvaa Havvaa",
    titleMl: "അവ്വാ ഹവ്വാ",
    movie: "Sathyam Sivam Sundaram",
    year: 2000,
    composer: "Vidyasagar",
    singer: "Mano & Swarnalatha",
    vibe: "mass",
  },
  {
    youtubeId: "fZc-rUPXkuU",
    title: "Manimuttathavani Panthal",
    titleMl: "മണിമുറ്റത്താവണി പന്തൽ",
    movie: "Dreams",
    year: 2000,
    composer: "Vidyasagar",
    singer: "K. J. Yesudas & Sujatha Mohan",
    vibe: "melody",
  },
  {
    youtubeId: "ydggK52urz8",
    title: "Pazhanimala",
    titleMl: "പഴനിമല",
    movie: "Narasimham",
    year: 2000,
    composer: "M. G. Radhakrishnan",
    singer: "M. G. Sreekumar",
    vibe: "mass",
  },
  {
    youtubeId: "20ez9-sZz_Y",
    title: "Alare Govinda",
    titleMl: "ആളറേ ഗോവിന്ദാ",
    movie: "Kakkakuyil",
    year: 2001,
    composer: "Deepan Chatterjee",
    singer: "M. G. Sreekumar",
    vibe: "mass",
  },
  {
    youtubeId: "egvqvgvhV4c",
    title: "Allikalil Azhakalayo",
    titleMl: "അല്ലികളിൽ അഴകാളയോ",
    movie: "Praja",
    year: 2001,
    composer: "M. G. Radhakrishnan",
    singer: "M. G. Sreekumar & Sujatha Mohan",
    vibe: "mass",
  },
  {
    youtubeId: "7LcDxxhyXcE",
    title: "Chanchala Drutha Patha Thalam",
    titleMl: "ചഞ്ചല ദ്രുതപദ താളം",
    movie: "Ishtam",
    year: 2001,
    composer: "Mohan Sithara",
    singer: "K. S. Chithra",
    vibe: "mass",
  },
  {
    youtubeId: "K2HzgFNbk-8",
    title: "Kai Kottu Penne",
    titleMl: "കൈകൊട്ടു പെണ്ണേ",
    movie: "Karumaadikkuttan",
    year: 2001,
    composer: "Mohan Sithara",
    singer: "Kalabhavan Mani",
    vibe: "nadan",
  },
  {
    youtubeId: "ayNw1xYX7kU",
    title: "Pathinalam Raavinte",
    titleMl: "പതിനാലാം രാവിന്റെ",
    movie: "Sharjah To Sharjah",
    year: 2001,
    composer: "Mohan Sithara",
    singer: "M. G. Sreekumar",
    vibe: "mappila",
  },
  {
    youtubeId: "NTqJeVhkaR4",
    title: "Pottukuthedi",
    titleMl: "പൊട്ടുകുത്തേടി",
    movie: "Ravanaprabhu",
    year: 2001,
    composer: "Suresh Peters",
    singer: "Sreeram & Swarnalatha",
    vibe: "mass",
  },
  {
    youtubeId: "2Iazv6UhA5g",
    title: "Thakilu Pukilu",
    titleMl: "തകിലു പുകിലു",
    movie: "Ravanaprabhu",
    year: 2001,
    composer: "Suresh Peters",
    singer: "M. G. Sreekumar & Mohanlal",
    vibe: "mass",
  },
  {
    youtubeId: "HK8GDwrWHuU",
    title: "Varuthantoppam Olichuchadiya",
    titleMl: "വരുത്തന്റൊപ്പം ഒളിച്ചുചാടിയ",
    movie: "Aakashathile Paravakal",
    year: 2001,
    composer: "Sidhartha Vijayan",
    singer: "Kalabhavan Mani",
    vibe: "nadan",
  },
  {
    youtubeId: "JVL5TPMlG3o",
    title: "Manassil Midhuna Mazha",
    titleMl: "മനസ്സിൽ മിഥുനമഴ",
    movie: "Nandanam",
    year: 2002,
    composer: "Raveendran",
    singer: "M. G. Sreekumar",
    vibe: "melody",
  },
  {
    youtubeId: "44rq9KwohhA",
    title: "Mattu Pongal Masam",
    titleMl: "മാട്ടു പൊങ്കൽ മാസം",
    movie: "Phantom",
    year: 2002,
    composer: "Deva",
    singer: "S. P. Balasubrahmanyam",
    vibe: "mass",
  },
  {
    youtubeId: "2C_jHO1I8X4",
    title: "Sukhamaanee Nilaavu",
    titleMl: "സുഖമാണീ നിലാവ്",
    movie: "Nammal",
    year: 2002,
    composer: "Mohan Sithara",
    singer: "Jyotsna & Vidhu Prathap",
    vibe: "melody",
  },
  {
    youtubeId: "7EqdUVLeJBg",
    title: "Therirangum Mukile",
    titleMl: "തേരിറങ്ങും മുകിലേ",
    movie: "Mazhathullikkilukkam",
    year: 2002,
    composer: "Suresh Peters",
    singer: "P. Jayachandran",
    vibe: "melody",
  },
  {
    youtubeId: "lZpULD9Vv5c",
    title: "Thinkale Poothinkale",
    titleMl: "തിങ്കളേ പൂന്തിങ്കളേ",
    movie: "Kalyanaraman",
    year: 2002,
    composer: "Berny–Ignatius",
    singer: "M. G. Sreekumar & Afsal",
    vibe: "mass",
  },
  {
    youtubeId: "jThMo-G14kc",
    title: "Valakilukkana Kunjole",
    titleMl: "വളകിലുക്കണ കുഞ്ഞോളേ",
    movie: "Kanmashi",
    year: 2002,
    composer: "M. Jayachandran",
    singer: "Kalabhavan Mani",
    vibe: "nadan",
  },
  {
    youtubeId: "OC_n8n1zMls",
    title: "Valuthaayoru Marathinte",
    titleMl: "വലുതായൊരു മരത്തിന്റെ",
    movie: "Chathurangam",
    year: 2002,
    composer: "M. G. Sreekumar",
    singer: "M. G. Sreekumar & Mohanlal",
    vibe: "mass",
  },
  {
    youtubeId: "fmi5lOmAqls",
    title: "Viral Thottal Viriyunna",
    titleMl: "വിരൽ തൊട്ടാൽ വിരിയുന്ന",
    movie: "Phantom",
    year: 2002,
    composer: "Deva",
    singer: "K. S. Chithra & P. Jayachandran",
    vibe: "melody",
  },
  {
    youtubeId: "qMyXYzQPHY4",
    title: "Aalilathaaliyumaay",
    titleMl: "ആലിലത്താളിയുമായ്",
    movie: "Mizhi Randilum",
    year: 2003,
    composer: "Raveendran",
    singer: "P. Jayachandran",
    vibe: "melody",
  },
  {
    youtubeId: "mVdnueBm1dM",
    title: "Aaru Paranju",
    titleMl: "ആരു പറഞ്ഞു",
    movie: "Pulivaal Kalyaanam",
    year: 2003,
    composer: "Berny–Ignatius",
    singer: "K. S. Chithra & P. Jayachandran",
    vibe: "melody",
  },
  {
    youtubeId: "OvWKGj7DQtc",
    title: "Dingiri Dingiri",
    titleMl: "ഡിംഗിരി ഡിംഗിരി",
    movie: "Pattaalam",
    year: 2003,
    composer: "Vidyasagar",
    singer: "Alan & Kalyani",
    vibe: "mass",
  },
  {
    youtubeId: "lyeB62xV4zw",
    title: "Enthe Innum Vanneela",
    titleMl: "എന്തേ ഇന്നും വന്നീലാ",
    movie: "Gramaphone",
    year: 2003,
    composer: "Vidyasagar",
    singer: "P. Jayachandran",
    vibe: "melody",
  },
  {
    youtubeId: "O6yK8Mc6Hpw",
    title: "Enthe Innum Vanneela",
    titleMl: "എന്തേ ഇന്നും വന്നീലാ",
    movie: "Gramaphone",
    year: 2003,
    composer: "Vidyasagar",
    singer: "P. Jayachandran",
    vibe: "melody",
  },
  {
    youtubeId: "y9kfRbsxkDs",
    title: "Gujarathi Kaalthala Kettiya",
    titleMl: "ഗുജറാത്തി കാൽത്തള കെട്ടിയ",
    movie: "Pulivaal Kalyaanam",
    year: 2003,
    composer: "Berny–Ignatius",
    singer: "Jyotsna Radhakrishnan",
    vibe: "mass",
  },
  {
    youtubeId: "J3fuMJ6Dpsc",
    title: "Karkuzhali Then",
    titleMl: "കാർകുഴലീ തേൻ",
    movie: "Kasthooriman",
    year: 2003,
    composer: "M. Jayachandran",
    vibe: "melody",
  },
  {
    youtubeId: "fH-HT-UAYCI",
    title: "Karukare Karuthoru",
    titleMl: "കറുകറെ കറുത്തൊരു",
    movie: "Balettan",
    year: 2003,
    composer: "M. Jayachandran",
    singer: "Mohanlal",
    vibe: "mass",
  },
  {
    youtubeId: "Pg5SWsBgKnk",
    title: "Karuppinazhaku",
    titleMl: "കറുപ്പിനഴക്",
    movie: "Swapnakkoodu",
    year: 2003,
    composer: "Alex Paul",
    singer: "Rajesh Vijay, Pradeep Babu & Jyotsna",
    vibe: "mass",
  },
  {
    youtubeId: "pixeuHwj9t4",
    title: "Kasavinte Thattamittu",
    titleMl: "കസവിന്റെ തട്ടമിട്ട്",
    movie: "Kilichundan Mampazham",
    year: 2003,
    composer: "Vidyasagar",
    singer: "Vineeth Sreenivasan",
    vibe: "mappila",
  },
  {
    youtubeId: "tcX_101zP8M",
    title: "Kudamullakkadavil",
    titleMl: "കുടമുല്ലക്കടവിൽ",
    movie: "Vellithira",
    year: 2003,
    composer: "Alphons Joseph",
    singer: "Sujatha Mohan",
    vibe: "melody",
  },
  {
    youtubeId: "eY7Q0hnru7Q",
    title: "Marakkudayaal",
    titleMl: "മറക്കുടയാൽ",
    movie: "Manasinakkare",
    year: 2003,
    composer: "Ilaiyaraaja",
    singer: "M. G. Sreekumar",
    vibe: "mass",
  },
  {
    youtubeId: "voj0KMpE8oY",
    title: "Pamba Ganapathi",
    titleMl: "പമ്പാ ഗണപതി",
    movie: "Pattaalam",
    year: 2003,
    composer: "Vidyasagar",
    singer: "M. G. Sreekumar",
    vibe: "mass",
  },
  {
    youtubeId: "ctazx6Jza_c",
    title: "Parannu Vannoru",
    titleMl: "പറന്നു വന്നൊരു",
    movie: "Swapnam Kondu Thulaabhaaram",
    year: 2003,
    composer: "Ouseppachan",
    singer: "Santhosh Keshav & Vidhu Prathap",
    vibe: "melody",
  },
  {
    youtubeId: "lnUt3hoZvTI",
    title: "Sare Sare Sambare",
    titleMl: "സാരേ സാരേ സാംബരേ",
    movie: "Thilakkam",
    year: 2003,
    composer: "Kaithapram Viswanathan",
    singer: "Sujatha Mohan & Dileep",
    vibe: "mass",
  },
  {
    youtubeId: "blV_YykR9U8",
    title: "Shilayil Ninnum",
    titleMl: "ശിലയിൽ നിന്നും",
    movie: "Chronic Bachelor",
    year: 2003,
    composer: "Deepak Dev",
    singer: "Sujatha Mohan",
    vibe: "melody",
  },
  {
    youtubeId: "AaCtg4h-azw",
    title: "Thamaranoolinal",
    titleMl: "താമരനൂലിനാൽ",
    movie: "Mullavalliyum Thenmaavum",
    year: 2003,
    composer: "Ouseppachan",
    singer: "G. Venugopal",
    vibe: "melody",
  },
  {
    youtubeId: "XoSTsjKCGcI",
    title: "Ambalakkara Thechikavil",
    titleMl: "അമ്പലക്കര തെച്ചിക്കാവിൽ",
    movie: "Black",
    year: 2004,
    composer: "Alex Paul",
    singer: "M. G. Sreekumar",
    vibe: "mass",
  },
  {
    youtubeId: "v0OJRzjR3cc",
    title: "Chentharmizhi",
    titleMl: "ചെന്താർമിഴി",
    movie: "Perumazhakkalam",
    year: 2004,
    composer: "M. Jayachandran",
    singer: "Madhu Balakrishnan & K. S. Chithra",
    vibe: "melody",
  },
  {
    youtubeId: "9T2KK-L9a4E",
    title: "Kandu Kandu",
    titleMl: "കണ്ടു കണ്ടു",
    movie: "Mambazhakkalam",
    year: 2004,
    composer: "M. Jayachandran",
    singer: "Sujatha Mohan",
    vibe: "mass",
  },
  {
    youtubeId: "k_81OMJCmjQ",
    title: "Kuttanadan Kaayalile",
    titleMl: "കുട്ടനാടൻ കായലിലെ",
    movie: "Kaazhcha",
    year: 2004,
    composer: "Mohan Sithara",
    singer: "Kalabhavan Mani & Madhu Balakrishnan",
    vibe: "nadan",
  },
  {
    youtubeId: "L-kKWXZ5wwc",
    title: "Kuttanadan Kayalile",
    titleMl: "കുട്ടനാടൻ കായലിലെ",
    movie: "Kaazhcha",
    year: 2004,
    composer: "Mohan Sithara",
    singer: "Madhu Balakrishnan & Kalabhavan Mani",
    vibe: "nadan",
  },
  {
    youtubeId: "MCrtP7_wvcY",
    title: "Maamazhayile",
    titleMl: "മാമഴയിലേ",
    movie: "Mayilaattam",
    year: 2004,
    composer: "M. Jayachandran",
    singer: "Sujatha Mohan",
    vibe: "melody",
  },
  {
    youtubeId: "LlGajmW_qb8",
    title: "Maattupetti Koyilile",
    titleMl: "മാട്ടുപ്പെട്ടി കോയിലിലെ",
    movie: "Mayilaattam",
    year: 2004,
    composer: "M. Jayachandran",
    singer: "Afsal & Chithra Iyer",
    vibe: "nadan",
  },
  {
    youtubeId: "CHVNf3r2PJc",
    title: "Mehruba",
    titleMl: "മെഹ്‌റുബാ",
    movie: "Perumazhakkalam",
    year: 2004,
    composer: "M. Jayachandran",
    singer: "Afsal & Jyotsna",
    vibe: "mappila",
  },
  {
    youtubeId: "2YKbSFmQh1Y",
    title: "Nillu Nillu Ente Neelakuyile",
    titleMl: "നില്ലു നില്ലു എന്റെ നീലക്കുയിലേ",
    movie: "Rain Rain Come Again",
    year: 2004,
    composer: "Jassie Gift",
    singer: "Jassie Gift",
    vibe: "mass",
  },
  {
    youtubeId: "-4Wl2fHHAVs",
    title: "Themma Themma",
    titleMl: "തെമ്മാ തെമ്മാ",
    movie: "Rain Rain Come Again",
    year: 2004,
    composer: "Jassie Gift",
    singer: "Jyotsna Radhakrishnan & Jassie Gift",
    vibe: "mass",
  },
  {
    youtubeId: "x5lkCfDqQhk",
    title: "Aararum Kaanathe",
    titleMl: "ആരാരും കാണാതെ",
    movie: "Chandrolsavam",
    year: 2005,
    composer: "Vidyasagar",
    singer: "P. Jayachandran",
    vibe: "melody",
  },
  {
    youtubeId: "j0zjwVeqn6c",
    title: "Etho Raathrimazha",
    titleMl: "ഏതോ രാത്രിമഴ",
    movie: "Bus Conductor",
    year: 2005,
    composer: "M. Jayachandran",
    singer: "K. J. Yesudas",
    vibe: "melody",
  },
  {
    youtubeId: "8tIoSxvzD3o",
    title: "Intha Panchayathile",
    titleMl: "ഇന്ത പഞ്ചായത്തിലെ",
    movie: "Pandippada",
    year: 2005,
    composer: "Suresh Peters",
    singer: "Afsal & Sujatha Mohan",
    vibe: "mass",
  },
  {
    youtubeId: "qmOsWxblWd8",
    title: "Karale Karalinte Karale",
    titleMl: "കരളേ കരളിന്റെ കരളേ",
    movie: "Udayananu Thaaram",
    year: 2005,
    composer: "Deepak Dev",
    singer: "Vineeth Sreenivasan",
    vibe: "mass",
  },
  {
    youtubeId: "aceDEQpRnZE",
    title: "Maanathe Manichithathe",
    titleMl: "മാനത്തെ മണിച്ചിത്തത്തേ",
    movie: "Bus Conductor",
    year: 2005,
    composer: "M. Jayachandran",
    singer: "Madhu Balakrishnan & Rimi Tomy",
    vibe: "mass",
  },
  {
    youtubeId: "kg1Dj9cbZOk",
    title: "Pinakkamaano Ennodinakkamano",
    titleMl: "പിണക്കമാണോ എന്നോടിണക്കമാണോ",
    movie: "Ananthabhadram",
    year: 2005,
    composer: "M. G. Radhakrishnan",
    singer: "M. G. Sreekumar & Manjari",
    vibe: "mass",
  },
  {
    youtubeId: "GxM0cF9lTuo",
    title: "Ramzan Nilavotha Pennalle",
    titleMl: "റംസാൻ നിലാവൊത്ത പെണ്ണല്ലേ",
    movie: "Boy Friend",
    year: 2005,
    composer: "M. Jayachandran",
    singer: "K. J. Yesudas",
    vibe: "mappila",
  },
  {
    youtubeId: "Ppo3oPo4NYw",
    title: "Velmuruka Harohara",
    titleMl: "വേൽമുരുകാ ഹരോഹര",
    movie: "Naran",
    year: 2005,
    composer: "Deepak Dev",
    singer: "M. G. Sreekumar",
    vibe: "mass",
  },
  {
    youtubeId: "Qsyzi89H9jA",
    title: "Chirimanimulle",
    titleMl: "ചിരിമണിമുല്ലേ",
    movie: "Lion",
    year: 2006,
    composer: "Deepak Dev",
    singer: "Jyotsna Radhakrishnan",
    vibe: "mass",
  },
  {
    youtubeId: "nSSZvroFmtc",
    title: "Kaattadi",
    titleMl: "കാറ്റാടി",
    movie: "Classmates",
    year: 2006,
    composer: "Alex Paul",
    singer: "Vidhu Prathap",
    vibe: "mass",
  },
  {
    youtubeId: "pmrUtMlzEFU",
    title: "Kando Kando",
    titleMl: "കണ്ടോ കണ്ടോ",
    movie: "Mahasamudram",
    year: 2006,
    composer: "M. Jayachandran",
    singer: "G. Venugopal & K. S. Chithra",
    vibe: "mass",
  },
  {
    youtubeId: "pJp3QEwe6EU",
    title: "Chellathamare",
    titleMl: "ചെല്ലത്താമരേ",
    movie: "Hallo",
    year: 2007,
    composer: "Alex Paul",
    singer: "K. S. Chithra & Sangeetha",
    vibe: "melody",
  },
  {
    youtubeId: "mdsH0Nzsddk",
    title: "Dum Dum Dum Dooreyetho",
    titleMl: "ഡും ഡും ഡും ദൂരെയേതോ",
    movie: "Raakkilippaattu",
    year: 2007,
    composer: "Vidyasagar",
    singer: "K. S. Chithra & Sujatha Mohan",
    vibe: "melody",
  },
  {
    youtubeId: "qhDckqdeBQE",
    title: "Mazhavillin",
    titleMl: "മഴവില്ലിൻ",
    movie: "Hallo",
    year: 2007,
    composer: "Alex Paul",
    singer: "Afsal & Manjari",
    vibe: "mass",
  },
  {
    youtubeId: "Y2df-yFAIR4",
    title: "Muthumazha",
    titleMl: "മുത്തുമഴ",
    movie: "Big B",
    year: 2007,
    composer: "Alphons Joseph",
    singer: "Vineeth Sreenivasan & Jyotsna",
    vibe: "melody",
  },
  {
    youtubeId: "lJXo0UjrPbg",
    title: "Oru Venal Puzhayil",
    titleMl: "ഒരു വേനൽ പുഴയിൽ",
    movie: "Pranayakaalam",
    year: 2007,
    composer: "Ouseppachan",
    singer: "Ranjith",
    vibe: "melody",
  },
  {
    youtubeId: "osrG_d26YRg",
    title: "Ravereyaay",
    titleMl: "രാവേറെയായ്",
    movie: "Rock N Roll",
    year: 2007,
    composer: "Vidyasagar",
    singer: "Madhu Balakrishnan",
    vibe: "melody",
  },
  {
    youtubeId: "1ci219EAqJA",
    title: "Sarike Ninne Kanan",
    titleMl: "ശാരികേ നിന്നെ കാണാൻ",
    movie: "Raakkilippaattu",
    year: 2007,
    composer: "Vidyasagar",
    singer: "K. S. Chithra & Sujatha Mohan",
    vibe: "melody",
  },
  {
    youtubeId: "XpoyMxq48y8",
    title: "Aarumukhan Munnil Chennu",
    titleMl: "ആറുമുഖൻ മുന്നിൽ ചെന്നു",
    movie: "Mulla",
    year: 2008,
    composer: "Vidyasagar",
    singer: "Rimi Tomy",
    vibe: "melody",
  },
  {
    youtubeId: "q_mhyW9d3e0",
    title: "Gokulapala Balaka",
    titleMl: "ഗോകുലപാല ബാലക",
    movie: "Parthan Kanda Paralokam",
    year: 2008,
    composer: "M. Jayachandran",
    singer: "Jassie Gift",
    vibe: "mass",
  },
  {
    youtubeId: "Vbma1brQX-Q",
    title: "Changazhi Muthumayi",
    titleMl: "ചങ്ങഴി മുത്തുമായി",
    movie: "Loudspeaker",
    year: 2009,
    composer: "Bijibal",
    singer: "Mammootty",
    vibe: "mass",
  },
  {
    youtubeId: "Gtrhjlhw2rk",
    title: "Koovaram Kili Paithale",
    titleMl: "കൂവരം കിളി പൈതലേ",
    movie: "Banaras",
    year: 2009,
    composer: "M. Jayachandran",
    singer: "Vijay Yesudas & Shweta Mohan",
    vibe: "melody",
  },

  /* ── the 2010s ────────────────────────────────────────────────────────── */
  {
    youtubeId: "IwysyMb26Zg",
    title: "Manikinavin Kothumbuvallam",
    titleMl: "മണിക്കിനാവിൻ കൊതുമ്പുവള്ളം",
    movie: "Pokkiri Raja",
    year: 2010,
    composer: "Jassie Gift",
    singer: "K. J. Yesudas & Sujatha Mohan",
    vibe: "melody",
  },
  {
    youtubeId: "sWT_V7XyDKs",
    title: "Ona Veyil Olangalil",
    titleMl: "ഓണവെയിൽ ഓളങ്ങളിൽ",
    movie: "Bombay March 12",
    year: 2011,
    composer: "Afzal Yusuff",
    singer: "M. G. Sreekumar",
    vibe: "melody",
  },
  {
    youtubeId: "cE1vnvXPJJ4",
    title: "Pathinezhinte Poonkaralil",
    titleMl: "പതിനേഴിന്റെ പൂങ്കരളിൽ",
    movie: "Vellaripravinte Changathi",
    year: 2011,
    composer: "Mohan Sithara",
    singer: "Kabeer & Shreya Ghoshal",
    vibe: "melody",
  },
  {
    youtubeId: "X48wPny1hTw",
    title: "Anuraagathin Velayil",
    titleMl: "അനുരാഗത്തിൻ വേളയിൽ",
    movie: "Thattathin Marayathu",
    year: 2012,
    composer: "Shaan Rahman",
    singer: "Vineeth Sreenivasan",
    vibe: "melody",
  },
  {
    youtubeId: "ULy7ACGybOM",
    title: "Appangalembadum",
    titleMl: "അപ്പങ്ങളെമ്പാടും",
    movie: "Ustad Hotel",
    year: 2012,
    composer: "Gopi Sundar",
    singer: "Anna Katharina Valayil",
    vibe: "nadan",
  },
  {
    youtubeId: "ZwXiooPGLjQ",
    title: "Kakka Malayile",
    titleMl: "കാക്ക മലയിലെ",
    movie: "Mallu Singh",
    year: 2012,
    composer: "M. Jayachandran",
    singer: "Alex",
    vibe: "mass",
  },
  {
    youtubeId: "Xq2GDrTNTXE",
    title: "Muthuchippi Poloru",
    titleMl: "മുത്തുച്ചിപ്പി പോലൊരു",
    movie: "Thattathin Marayathu",
    year: 2012,
    composer: "Shaan Rahman",
    singer: "Sachin Warrier & Ramya Nambeeshan",
    vibe: "melody",
  },
  {
    youtubeId: "0ezn5lcbQmc",
    title: "Rab Rab Rab",
    titleMl: "റബ് റബ് റബ്",
    movie: "Mallu Singh",
    year: 2012,
    composer: "M. Jayachandran",
    singer: "Shankar Mahadevan",
    vibe: "mass",
  },
  {
    youtubeId: "6nngUnGZ5sY",
    title: "Kanni Penne",
    titleMl: "കന്നിപ്പെണ്ണേ",
    movie: "Sound Thoma",
    year: 2013,
    composer: "Gopi Sundar",
    singer: "Shankar Mahadevan & Rimi Tomy",
    vibe: "mass",
  },
  {
    youtubeId: "SuuypjzzqRw",
    title: "Pista",
    titleMl: "പിസ്ത",
    movie: "Neram",
    year: 2013,
    composer: "Rajesh Murugesan",
    singer: "Shabareesh Varma",
    vibe: "mass",
  },
  {
    youtubeId: "r3fhuJJRcYc",
    title: "Vaathil Melle",
    titleMl: "വാതിൽ മെല്ലെ",
    movie: "Neram",
    year: 2013,
    composer: "Rajesh Murugesan",
    singer: "Sachin Warrier",
    vibe: "melody",
  },
  {
    youtubeId: "Qs2ta9_CaKM",
    title: "Kaattu Mooliyo",
    titleMl: "കാറ്റ് മൂളിയോ",
    movie: "Ohm Shanthi Oshaana",
    year: 2014,
    composer: "Shaan Rahman",
    singer: "Vineeth Sreenivasan",
    vibe: "mass",
  },
  {
    youtubeId: "qHnd9Hls12w",
    title: "Aluva Puzhayude Theerathu",
    titleMl: "ആലുവാ പുഴയുടെ തീരത്ത്",
    movie: "Premam",
    year: 2015,
    composer: "Rajesh Murugesan",
    singer: "Vineeth Sreenivasan",
    vibe: "mass",
  },
  {
    youtubeId: "flISEBsDSH8",
    title: "Kaathirunnu Kaathirunnu",
    titleMl: "കാത്തിരുന്നു കാത്തിരുന്നു",
    movie: "Ennu Ninte Moideen",
    year: 2015,
    composer: "M. Jayachandran",
    singer: "Shreya Ghoshal",
    vibe: "melody",
  },
  {
    youtubeId: "ewDnUX2x8Ro",
    title: "Malare",
    titleMl: "മലരേ",
    movie: "Premam",
    year: 2015,
    composer: "Rajesh Murugesan",
    singer: "Vijay Yesudas",
    vibe: "melody",
  },
  {
    youtubeId: "ehj1UpZJSrA",
    title: "Ullasa Gaayike",
    titleMl: "ഉല്ലാസ ഗായികേ",
    movie: "Adi Kapyare Koottamani",
    year: 2015,
    composer: "Shaan Rahman",
    singer: "Vidhu Prathap",
    vibe: "mass",
  },
  {
    youtubeId: "VNg556FUOUs",
    title: "Arikil Pathiye",
    titleMl: "അരികിൽ പതിയേ",
    movie: "Oru Murai Vanthu Paarthaya",
    year: 2016,
    composer: "Vinu Thomas",
    singer: "Najeem Arshad",
    vibe: "melody",
  },
  {
    youtubeId: "bRYaCXVW7Hg",
    title: "Dooreyo",
    titleMl: "ദൂരെയോ",
    movie: "Aanandam",
    year: 2016,
    composer: "Sachin Warrier",
    singer: "Vishak Nair & Sachin Warrier",
    vibe: "melody",
  },
  {
    youtubeId: "ogrgI9aH_K0",
    title: "Minnaminnikkum",
    titleMl: "മിന്നാമിന്നിക്കും",
    movie: "Kattappanayile Ritwik Roshan",
    year: 2016,
    vibe: "mass",
  },
  {
    youtubeId: "UsJkhu8K1gs",
    title: "Aaro Nenjil",
    titleMl: "ആരോ നെഞ്ചിൽ",
    movie: "Godha",
    year: 2017,
    composer: "Shaan Rahman",
    singer: "Gowry Lekshmi",
    vibe: "melody",
  },
  {
    youtubeId: "FXiaIH49oAU",
    title: "Entammede Jimikki Kammal",
    titleMl: "എന്റമ്മേടെ ജിമിക്കി കമ്മൽ",
    movie: "Velipadinte Pusthakam",
    year: 2017,
    composer: "Shaan Rahman",
    singer: "Vineeth Sreenivasan & Renjith Unni",
    vibe: "mass",
  },
  {
    youtubeId: "YRrbcn37rbE",
    title: "Jillam Jillala",
    titleMl: "ജില്ലം ജില്ലാല",
    movie: "Honey Bee 2",
    year: 2017,
    composer: "Deepak Dev",
    singer: "Afsal, Rimi Tomy & Anwar",
    vibe: "mass",
  },
  {
    youtubeId: "FAn2i7gu32w",
    title: "Lailakame",
    titleMl: "ലൈലാകമേ",
    movie: "Ezra",
    year: 2017,
    composer: "Rahul Raj",
    singer: "Haricharan",
    vibe: "melody",
  },
  {
    youtubeId: "53Qn0CJ4ws8",
    title: "Vaanam Thilathilakkanu",
    titleMl: "വാനം തിളതിളക്കണ്",
    movie: "Comrade in America",
    year: 2017,
    composer: "Gopi Sundar",
    singer: "Dulquer Salmaan",
    vibe: "mass",
  },
  {
    youtubeId: "DInfmi-YIiw",
    title: "Jeevamshamayi",
    titleMl: "ജീവാംശമായ്",
    movie: "Theevandi",
    year: 2018,
    composer: "Kailas Menon",
    singer: "Shreya Ghoshal & Harisankar K. S.",
    vibe: "melody",
  },
  {
    youtubeId: "3y4OWH92Ic4",
    title: "Karineela Kannulla",
    titleMl: "കരിനീല കണ്ണുള്ള",
    movie: "Joseph",
    year: 2018,
    composer: "Ranjin Raj",
    singer: "Karthik & Akhila Anand",
    vibe: "melody",
  },
  {
    youtubeId: "W0fKl43QmIE",
    title: "Manikya Malaraya Poovi",
    titleMl: "മാണിക്യ മലരായ പൂവി",
    movie: "Oru Adaar Love",
    year: 2018,
    composer: "Shaan Rahman",
    singer: "Vineeth Sreenivasan",
    vibe: "mappila",
  },
  {
    youtubeId: "RSL1-rvGmj4",
    title: "Podipaarana",
    titleMl: "പൊടിപാറണ",
    movie: "Queen",
    year: 2018,
    composer: "Jakes Bejoy",
    singer: "Ajaey Shravan & Kesav Vinod",
    vibe: "mass",
  },
  {
    youtubeId: "vjKFXhucXIU",
    title: "Poomuthole",
    titleMl: "പൂമുത്തോളേ",
    movie: "Joseph",
    year: 2018,
    composer: "Ranjin Raj",
    singer: "Vijay Yesudas",
    vibe: "melody",
  },
  {
    youtubeId: "HIrC-X_JKQw",
    title: "Ezhuthaakadha",
    titleMl: "എഴുതാകഥ",
    movie: "Kumbalangi Nights",
    year: 2019,
    composer: "Sushin Shyam",
    vibe: "mass",
  },
  {
    youtubeId: "P7-xs4XF4CA",
    title: "Kudukku",
    titleMl: "കുടുക്ക്",
    movie: "Love Action Drama",
    year: 2019,
    composer: "Shaan Rahman",
    singer: "Vineeth Sreenivasan",
    vibe: "mass",
  },
  {
    youtubeId: "bY_LdUERXjQ",
    title: "Neeyilla Neram",
    titleMl: "നീയില്ലാ നേരം",
    movie: "Luca",
    year: 2019,
    composer: "Sooraj S. Kurup",
    singer: "Sooraj S. Kurup & Deepa Palanad",
    vibe: "melody",
  },
  {
    youtubeId: "P-jKtzUuVcM",
    title: "Pavizha Mazha",
    titleMl: "പവിഴമഴ",
    movie: "Athiran",
    year: 2019,
    composer: "P. S. Jayhari",
    singer: "K. S. Harisankar",
    vibe: "melody",
  },
  {
    youtubeId: "ZKhOs_Pc_7s",
    title: "Uyiril Thodum",
    titleMl: "ഉയിരിൽ തൊടും",
    movie: "Kumbalangi Nights",
    year: 2019,
    composer: "Sushin Shyam",
    singer: "Sooraj Santhosh",
    vibe: "melody",
  },

  /*
   * ── undated ──────────────────────────────────────────────────────────────
   *
   * Songs no public source dates — mostly നാടൻ and മാപ്പിള album tracks, older than
   * the recording and belonging to whoever is singing them. They carry no year rather
   * than a confident invention.
   */
  {
    youtubeId: "JXRwKIpetEY",
    title: "Akhila Charachara Paripalakan Nee",
    titleMl: "അഖില ചരാചര പരിപാലകൻ നീ",
    movie: "Mappila album",
    singer: "Bappu Velliparamba",
    vibe: "mappila",
  },
  {
    youtubeId: "vrQzJJ3tI7k",
    title: "Ambalappuzhe Unnikkannanodu",
    titleMl: "അമ്പലപ്പുഴെ ഉണ്ണിക്കണ്ണനോട്",
    movie: "Adhwaytham",
    composer: "M. G. Radhakrishnan",
    singer: "M. G. Sreekumar & K. S. Chithra",
    vibe: "nadan",
  },
  {
    youtubeId: "1Ea9bStI6ik",
    title: "Ammayeede Mole",
    titleMl: "അമ്മായീടെ മോളെ",
    movie: "Kalabhavan Mani",
    singer: "Kalabhavan Mani",
    vibe: "mappila",
  },
  {
    youtubeId: "QM2GqxBoAJI",
    title: "Anthi Kannathunna Nerathu",
    titleMl: "അന്തി കണ്ണത്തുന്ന നേരത്ത്",
    movie: "Madhu Mundakam",
    vibe: "nadan",
  },
  {
    youtubeId: "QYWO_s2gwOs",
    title: "Arippodi Jeerakam",
    titleMl: "അരിപ്പൊടി ജീരകം മഞ്ഞളുകൊത്തമല്ലി",
    movie: "Kalabhavan Mani",
    singer: "Kalabhavan Mani",
    vibe: "nadan",
  },
  {
    youtubeId: "snNjfsUrRUU",
    title: "Athippazhathinnilanneer",
    titleMl: "അത്തിപ്പഴത്തിന്നിളന്നീർ ചുരത്തും",
    movie: "Nakshathrakkoodaram",
    vibe: "mass",
  },
  {
    youtubeId: "4iCJHcUCeMI",
    title: "Balettan Molalledi",
    titleMl: "ബാലേട്ടൻ മോളല്ലേടി",
    movie: "Kattile Kaatana",
    composer: "Kalabhavan Mani",
    singer: "Kalabhavan Mani",
    vibe: "nadan",
  },
  {
    youtubeId: "tRaJPNNjK6M",
    title: "Chalakkudikkaran Changathi",
    titleMl: "ചാലക്കുടിക്കാരൻ ചങ്ങാതി",
    movie: "Nadan Pattukal",
    composer: "Kalabhavan Mani",
    singer: "Kalabhavan Mani",
    vibe: "nadan",
  },
  {
    youtubeId: "F6nHLPyVftc",
    title: "Chembaneer Poo Polen",
    titleMl: "ചെമ്പനീർ പൂ പോലെൻ",
    movie: "Ennu Nathante Nimmi",
    singer: "K. J. Yesudas",
    vibe: "melody",
  },
  {
    youtubeId: "RTnIbiL8PfY",
    title: "Doore Kannadi Puzha",
    titleMl: "ദൂരെ കണ്ണാടി പുഴ",
    movie: "Mappila album",
    singer: "Afsal",
    vibe: "mappila",
  },
  {
    youtubeId: "D5bqlweWjCs",
    title: "Engupoyi En Seethe",
    titleMl: "എങ്ങുപോയി എൻ സീതേ",
    movie: "Padan Kothicha Paattukal",
    composer: "Arumughan Venkidangu",
    singer: "Kalabhavan Mani",
    vibe: "nadan",
  },
  {
    youtubeId: "pTgtApG9UlY",
    title: "Enikkum Undoru Kunjuvaava",
    titleMl: "എനിക്കും ഉണ്ടൊരു കുഞ്ഞുവാവ",
    movie: "Kalabhavan Mani",
    singer: "Kalabhavan Mani",
    vibe: "nadan",
  },
  {
    youtubeId: "fb4679Vpj2Q",
    title: "Enikkumundoru Beevi",
    titleMl: "എനിക്കുമുണ്ടൊരു ബീവി",
    movie: "Kalabhavan Mani",
    singer: "Kalabhavan Mani",
    vibe: "mappila",
  },
  {
    youtubeId: "utnmEXUkdhM",
    title: "Guna Gunasseri",
    titleMl: "ഗുണ ഗുണശ്ശേരി",
    movie: "Kalabhavan Mani",
    singer: "Kalabhavan Mani",
    vibe: "nadan",
  },
  {
    youtubeId: "50jWa5Ax4L8",
    title: "Ikkollam Namukku",
    titleMl: "ഇക്കൊല്ലം നമ്മക്ക്",
    movie: "Kalabhavan Mani",
    singer: "Kalabhavan Mani",
    vibe: "nadan",
  },
  {
    youtubeId: "r_Kwt7Q7YY4",
    title: "Jeevante Jeevanaam",
    titleMl: "ജീവന്റെ ജീവനാം കൂട്ടുകാരാ",
    movie: "Ormakkai",
    composer: "M. Jayachandran",
    vibe: "melody",
  },
  {
    youtubeId: "fzK-ldu_le0",
    title: "Kaavungaatte Ambalathil",
    titleMl: "കാവുങ്ങാട്ടെ അമ്പലത്തില്",
    movie: "Kalabhavan Mani",
    singer: "Kalabhavan Mani",
    vibe: "nadan",
  },
  {
    youtubeId: "y9yQ-kxIGOU",
    title: "Kadakkanninmunakonden",
    titleMl: "കടക്കണ്ണിൻമുനകൊണ്ടെൻ",
    movie: "Mappilappattukal",
    composer: "Kalabhavan Mani",
    singer: "Kalabhavan Mani",
    vibe: "mappila",
  },
  {
    youtubeId: "CzNbap-VNYA",
    title: "Kalkkandam Chundil",
    titleMl: "കൽക്കണ്ടം ചുണ്ടിൽ",
    movie: "Onnanu Nammal",
    vibe: "mass",
  },
  {
    youtubeId: "crBcb87h7-k",
    title: "Kannimaanga Praayathil",
    titleMl: "കണ്ണിമാങ്ങാ പ്രായത്തിൽ",
    movie: "Kalabhavan Mani",
    singer: "Kalabhavan Mani",
    vibe: "nadan",
  },
  {
    youtubeId: "dDEtJrvYZpI",
    title: "Kanniprasavam",
    titleMl: "കന്നിപ്രസവം",
    movie: "Mappilappattukal",
    composer: "Kalabhavan Mani",
    singer: "Kalabhavan Mani",
    vibe: "mappila",
  },
  {
    youtubeId: "GSaLsSTd-WU",
    title: "Kunjunnaalil",
    titleMl: "കുഞ്ഞുന്നാളിൽ",
    movie: "Nadan Pattukal",
    composer: "Kalabhavan Mani",
    singer: "Kalabhavan Mani",
    vibe: "nadan",
  },
  {
    youtubeId: "M1_VFAFP2WM",
    title: "Kuttanadan Punchayile",
    titleMl: "കുട്ടനാടൻ പുഞ്ചയിലെ",
    movie: "Kaavalam Chundan",
    composer: "Traditional",
    singer: "K. J. Yesudas",
    vibe: "nadan",
  },
  {
    youtubeId: "XfqWftKayFY",
    title: "Laile Laile Swargapoo",
    titleMl: "ലൈലേ ലൈലേ സ്വർഗപ്പൂ",
    movie: "Kalbhanu Fathima",
    composer: "M. Kunji Moosa",
    singer: "Afsal",
    vibe: "mappila",
  },
  {
    youtubeId: "euZWAFbjjys",
    title: "Lavudhikkana Neramayitha",
    titleMl: "ലാവുദിക്കണ നേരമായിതാ",
    movie: "Mambazhathin Chelanu",
    composer: "Shyam Dharman",
    singer: "Shanu",
    vibe: "mappila",
  },
  {
    youtubeId: "cFlQDxVvIHY",
    title: "Maari Poomari",
    titleMl: "മാരി പൂമാരി",
    movie: "Nadan Pattukal",
    composer: "Kalabhavan Mani",
    singer: "Kalabhavan Mani",
    vibe: "nadan",
  },
  {
    youtubeId: "h3XBSfpNpZU",
    title: "Mahiyil Maha Seenennu",
    titleMl: "മഹിയിൽ മഹാ സീനെന്ന്",
    movie: "Mappila album",
    vibe: "mappila",
  },
  {
    youtubeId: "e0qtyvOrfQI",
    title: "Makaramaasam Vannaduthille",
    titleMl: "മകരമാസം വന്നടുത്തില്ലേ",
    movie: "Kalabhavan Mani",
    singer: "Kalabhavan Mani",
    vibe: "nadan",
  },
  {
    youtubeId: "EOYuORbxB9s",
    title: "Mangalyam Kazhikkathe",
    titleMl: "മംഗല്യം കഴിക്കാതെ",
    movie: "Kalbhanu Fathima",
    composer: "M. Kunji Moosa",
    singer: "Thajudeen Vadakara",
    vibe: "mappila",
  },
  {
    youtubeId: "sJpMe4rfspg",
    title: "Manjin Chirakulla Vellaripravu",
    titleMl: "മഞ്ഞിൻ ചിറകുള്ള വെള്ളരി",
    movie: "Swagatham",
    vibe: "melody",
  },
  {
    youtubeId: "W9xwbIaMAZg",
    title: "Missirile Rajathi",
    titleMl: "മിസിരിലെ രാജാത്തി",
    movie: "Mappila album",
    vibe: "mappila",
  },
  {
    youtubeId: "v1Kj7voPD2o",
    title: "Nenjinullil Neeyanu",
    titleMl: "നെഞ്ചിനുള്ളിൽ നീയാണ്",
    movie: "Kalbhanu Fathima",
    singer: "Thajudeen Vadakara",
    vibe: "mappila",
  },
  {
    youtubeId: "roP9RKDmyko",
    title: "Nenjukkulle Neethane",
    titleMl: "നെഞ്ചുക്കുള്ളേ നീതാനെ",
    movie: "Dile He Fathima",
    composer: "Thej Mervin",
    singer: "Thajudeen Vadakara",
    vibe: "mappila",
  },
  {
    youtubeId: "0QSr9S73gtU",
    title: "Njan Kudikkana Kanjeelenthinu",
    titleMl: "ഞാൻ കുടിക്കണ കഞ്ഞീലെന്തിന്",
    movie: "Nadan Pattukal",
    composer: "Kalabhavan Mani",
    singer: "Kalabhavan Mani",
    vibe: "nadan",
  },
  {
    youtubeId: "WaNE4m-WTpw",
    title: "Odakkombil Kaattu Kinungippoy",
    titleMl: "ഓടക്കൊമ്പിൽ കാറ്റുകിണുങ്ങിപ്പോയ്",
    movie: "Samooham",
    vibe: "melody",
  },
  {
    youtubeId: "YYZWi3OQqWw",
    title: "Odapazham Poloru Pennu",
    titleMl: "ഓടപ്പഴം പോലൊരു പെണ്ണ്",
    movie: "Nadan Pattukal",
    composer: "Kalabhavan Mani",
    singer: "Kalabhavan Mani",
    vibe: "nadan",
  },
  {
    youtubeId: "Yr73x3U8OPQ",
    title: "Oru Venpiravu",
    titleMl: "ഒരു വെൺപിറാവു",
    movie: "Newspaper Boy",
    vibe: "melody",
  },
  {
    youtubeId: "av8Di_5FYMA",
    title: "Paalnila Punchiri",
    titleMl: "പാൽനിലാ പുഞ്ചിരി",
    movie: "Midad",
    composer: "K. A. Latheef",
    singer: "K. G. Markose",
    vibe: "mappila",
  },
  {
    youtubeId: "n-cmMyJ--M8",
    title: "Palnila Punchiri",
    titleMl: "പാൽനിലാ പുഞ്ചിരി",
    movie: "Midad",
    composer: "K. A. Latheef",
    singer: "Dana Razik",
    vibe: "mappila",
  },
  {
    youtubeId: "cWeqR9cJydM",
    title: "Panchara Kunchiyalle",
    titleMl: "പഞ്ചാര കുഞ്ചിയല്ലേ",
    movie: "Kalabhavan Mani",
    singer: "Kalabhavan Mani",
    vibe: "nadan",
  },
  {
    youtubeId: "f83NdG0nEI4",
    title: "Panchavarnakkulire",
    titleMl: "പഞ്ചവർണ്ണക്കുളിരേ",
    movie: "Suryaputhran",
    vibe: "mass",
  },
  {
    youtubeId: "DVz8UxXeuzU",
    title: "Penne Pedamane",
    titleMl: "പെണ്ണെ പേടമാനെ പേടിച്ചോടും",
    movie: "Kalabhavan Mani",
    singer: "Kalabhavan Mani",
    vibe: "nadan",
  },
  {
    youtubeId: "5mR2Fst3_x4",
    title: "Poonkattinodum",
    titleMl: "പൂങ്കറ്റിനോടും",
    movie: "Poomukhappadiyil Ninneyum Kaathu",
    vibe: "melody",
  },
  {
    youtubeId: "T19u38jSKqU",
    title: "Poovirinjallo",
    titleMl: "പൂവിരിഞ്ഞല്ലൊ അതു തേൻ",
    movie: "Puthiya Velicham",
    vibe: "mass",
  },
  {
    youtubeId: "7CgfRjRAfWA",
    title: "Punnaara Muthe",
    titleMl: "പുന്നാര മുത്തെ",
    movie: "Kalabhavan Mani",
    singer: "Kalabhavan Mani",
    vibe: "nadan",
  },
  {
    youtubeId: "CmdYPM-Zt5c",
    title: "Thennalaadum Poomarathin",
    titleMl: "തെന്നലാടും പൂമരത്തിൻ",
    movie: "Kandu Kandarinju",
    vibe: "melody",
  },
  {
    youtubeId: "41fqCThs_vc",
    title: "Umbaayi Kuchaandi",
    titleMl: "ഉമ്പായി കുച്ചാണ്ട്",
    movie: "Kalabhavan Mani",
    singer: "Kalabhavan Mani",
    vibe: "nadan",
  },
  {
    youtubeId: "7cSRke-WUAQ",
    title: "Uthradappoonilave Vaa",
    titleMl: "ഉത്രാടപ്പൂനിലാവേ വാ",
    movie: "Onappaattu",
    singer: "K. J. Yesudas",
    vibe: "nadan",
  },
];
