import type { Track } from "@/engine";

/**
 * The playlist. This file *is* the product — the engineering was the easy half.
 *
 * **Where these came from.** One place: the YouTube search
 * `https://www.youtube.com/results?search_query=bus+hits+malayalam`, and every
 * playlist that search surfaces. `.harvest/ytsearch.sh` dumps that pool (~1,700
 * rows, ~870 distinct single-song uploads) and `npm run mine-search` turns it into
 * ranked candidates by reading each upload's own metadata. What it has to throw
 * away is most of the job:
 *
 *  · **jukeboxes** — over a third of that search is 20-to-60-minute "non-stop bus
 *    playlist" uploads. Real listening, useless as tracks: one entry, no per-song
 *    metadata, no seek that means anything.
 *  · **not-Malayalam** — the playlists that search surfaces drift, so Tamil and
 *    Hindi come with them. A script test is not enough, because a Tamil upload's
 *    title is Latin: "Mersal", "Bigil" and "Vettaikaaran" all sailed through one.
 *  · **not-the-song** — remixes, DJ edits, covers, karaoke, status clips.
 *  · **metadata-less** — an upload that cannot yield a film and a singer is not a
 *    track this playlist can honestly carry.
 *
 * **The years are mine, not the uploads'.** Almost every description reports the
 * upload or copyright year — a 2005 song "from 2023" — so the year here is the
 * film's, and where a film's year is not something that can be stated plainly the
 * track carries none rather than a confident invention. Same for the two album
 * tracks at the bottom, which no public source dates.
 *
 * **Every ID is a label, studio or artist-channel upload wherever one exists**,
 * because those are the ones that stay up and stay embeddable. `npm run
 * check-tracks` proves each still resolves. Malayalam titles are typed by hand,
 * taking the official spelling from the upload title wherever it carried one.
 *
 * To suggest a song: it has to be in that search's pool. Re-run the harvest and the
 * miner, then open a pull request against this file.
 */
export const tracks: readonly Track[] = [
  /* ── the 80s and 90s, which never stopped playing on these routes ──────── */
  {
    youtubeId: "VnOLG5amCIQ",
    title: "Unnikale Oru Kadha Parayam",
    titleMl: "ഉണ്ണികളേ ഒരു കഥ പറയാം",
    movie: "Unnikale Oru Kadha Parayam",
    year: 1987,
    composer: "Ouseppachan",
    singer: "K. J. Yesudas",
    vibe: "melody",
  },
  {
    youtubeId: "TPkCqQgwcHE",
    title: "Athira Varavayi",
    titleMl: "അതിര വരവായി",
    movie: "Thudarkadha",
    year: 1991,
    composer: "S. P. Venkatesh",
    singer: "K. S. Chithra & M. G. Sreekumar",
    vibe: "melody",
  },
  {
    youtubeId: "LP45xF2gBxk",
    title: "Manju Manjeera",
    titleMl: "മഞ്ജു മഞ്ജീര",
    movie: "Aagneyam",
    year: 1993,
    composer: "Johnson",
    singer: "K. J. Yesudas",
    vibe: "melody",
  },
  {
    youtubeId: "vp24h6mbb_8",
    title: "Ammoommakkili",
    titleMl: "അമ്മൂമ്മക്കിളി",
    movie: "Chandralekha",
    year: 1997,
    composer: "Berny–Ignatius",
    singer: "K. S. Chithra",
    vibe: "melody",
  },
  {
    youtubeId: "rbYmz_JR-kc",
    title: "Choolamadichu Karangi Nadakkum",
    titleMl: "ചൂളമടിച്ചു കറങ്ങി നടക്കും",
    movie: "Summer in Bethlehem",
    year: 1998,
    composer: "Vidyasagar",
    singer: "K. S. Chithra",
    vibe: "mass",
  },
  {
    youtubeId: "fWeg0P36xcc",
    title: "Onnanam Kunninmel",
    titleMl: "ഒന്നാനാം കുന്നിന്മേൽ",
    movie: "Mayilppeelikkaavu",
    year: 1998,
    composer: "Berny–Ignatius",
    singer: "K. J. Yesudas & K. S. Chithra",
    vibe: "nadan",
  },
  {
    youtubeId: "TKHenjnkPnw",
    title: "Aavani Ponnoonjaal",
    titleMl: "ആവണി പൊന്നൂഞ്ഞാൽ",
    movie: "Kottaram Veettile Appoottan",
    year: 1998,
    composer: "Berny–Ignatius",
    singer: "M. G. Sreekumar",
    vibe: "mass",
  },
  {
    youtubeId: "TtwrONQlc-k",
    title: "Margazhiye Mallikaye",
    titleMl: "മാർഗഴിയേ മല്ലികയേ",
    movie: "Megham",
    year: 1999,
    composer: "Ouseppachan",
    singer: "M. G. Sreekumar & Srinivas",
    vibe: "mass",
  },

  /* ── the 2000s: the decade the back seat owned ────────────────────────── */
  {
    youtubeId: "6uEFZchRTqM",
    title: "Avvaa Havvaa",
    titleMl: "അവ്വാ ഹവ്വാ",
    movie: "Sathyam Sivam Sundaram",
    year: 2000,
    composer: "Vidyasagar",
    singer: "Mano & Swarnalatha",
    vibe: "mass",
  },
  {
    youtubeId: "fZc-rUPXkuU",
    title: "Manimuttathavani Panthal",
    titleMl: "മണിമുറ്റത്താവണി പന്തൽ",
    movie: "Dreams",
    year: 2000,
    composer: "Vidyasagar",
    singer: "K. J. Yesudas & Sujatha Mohan",
    vibe: "melody",
  },
  {
    youtubeId: "ydggK52urz8",
    title: "Pazhanimala",
    titleMl: "പഴനിമല",
    movie: "Narasimham",
    year: 2000,
    composer: "M. G. Radhakrishnan",
    singer: "M. G. Sreekumar",
    vibe: "mass",
  },
  {
    youtubeId: "K2HzgFNbk-8",
    title: "Kai Kottu Penne",
    titleMl: "കൈകൊട്ടു പെണ്ണേ",
    movie: "Karumaadikkuttan",
    year: 2001,
    composer: "Mohan Sithara",
    singer: "Kalabhavan Mani",
    vibe: "nadan",
  },
  {
    youtubeId: "20ez9-sZz_Y",
    title: "Alare Govinda",
    titleMl: "ആളറേ ഗോവിന്ദാ",
    movie: "Kakkakuyil",
    year: 2001,
    composer: "Deepan Chatterjee",
    singer: "M. G. Sreekumar",
    vibe: "mass",
  },
  {
    youtubeId: "ayNw1xYX7kU",
    title: "Pathinalam Raavinte",
    titleMl: "പതിനാലാം രാവിന്റെ",
    movie: "Sharjah To Sharjah",
    year: 2001,
    composer: "Mohan Sithara",
    singer: "M. G. Sreekumar",
    vibe: "mappila",
  },
  {
    youtubeId: "egvqvgvhV4c",
    title: "Allikalil Azhakalayo",
    titleMl: "അല്ലികളിൽ അഴകാളയോ",
    movie: "Praja",
    year: 2001,
    composer: "M. G. Radhakrishnan",
    singer: "M. G. Sreekumar & Sujatha Mohan",
    vibe: "mass",
  },
  {
    youtubeId: "jThMo-G14kc",
    title: "Valakilukkana Kunjole",
    titleMl: "വളകിലുക്കണ കുഞ്ഞോളേ",
    movie: "Kanmashi",
    year: 2002,
    composer: "M. Jayachandran",
    singer: "Kalabhavan Mani",
    vibe: "nadan",
  },
  {
    youtubeId: "lZpULD9Vv5c",
    title: "Thinkale Poothinkale",
    titleMl: "തിങ്കളേ പൂന്തിങ്കളേ",
    movie: "Kalyanaraman",
    year: 2002,
    composer: "Berny–Ignatius",
    singer: "M. G. Sreekumar & Afsal",
    vibe: "mass",
  },
  {
    youtubeId: "JVL5TPMlG3o",
    title: "Manassil Midhuna Mazha",
    titleMl: "മനസ്സിൽ മിഥുനമഴ",
    movie: "Nandanam",
    year: 2002,
    composer: "Raveendran",
    singer: "M. G. Sreekumar",
    vibe: "melody",
  },
  {
    youtubeId: "fmi5lOmAqls",
    title: "Viral Thottal Viriyunna",
    titleMl: "വിരൽ തൊട്ടാൽ വിരിയുന്ന",
    movie: "Phantom",
    year: 2002,
    composer: "Deva",
    singer: "K. S. Chithra & P. Jayachandran",
    vibe: "melody",
  },
  {
    youtubeId: "eY7Q0hnru7Q",
    title: "Marakkudayaal",
    titleMl: "മറക്കുടയാൽ",
    movie: "Manasinakkare",
    year: 2003,
    composer: "Ilaiyaraaja",
    singer: "M. G. Sreekumar",
    vibe: "mass",
  },
  {
    youtubeId: "AaCtg4h-azw",
    title: "Thamaranoolinal",
    titleMl: "താമരനൂലിനാൽ",
    movie: "Mullavalliyum Thenmaavum",
    year: 2003,
    composer: "Ouseppachan",
    singer: "G. Venugopal",
    vibe: "melody",
  },
  {
    youtubeId: "blV_YykR9U8",
    title: "Shilayil Ninnum",
    titleMl: "ശിലയിൽ നിന്നും",
    movie: "Chronic Bachelor",
    year: 2003,
    composer: "Deepak Dev",
    singer: "Sujatha Mohan",
    vibe: "melody",
  },
  {
    youtubeId: "lyeB62xV4zw",
    title: "Enthe Innum Vanneela",
    titleMl: "എന്തേ ഇന്നും വന്നീലാ",
    movie: "Gramaphone",
    year: 2003,
    composer: "Vidyasagar",
    singer: "P. Jayachandran",
    vibe: "melody",
  },
  {
    youtubeId: "OvWKGj7DQtc",
    title: "Dingiri Dingiri",
    titleMl: "ഡിംഗിരി ഡിംഗിരി",
    movie: "Pattaalam",
    year: 2003,
    composer: "Vidyasagar",
    singer: "Alan & Kalyani",
    vibe: "mass",
  },
  {
    youtubeId: "ctazx6Jza_c",
    title: "Parannu Vannoru",
    titleMl: "പറന്നു വന്നൊരു",
    movie: "Swapnam Kondu Thulaabhaaram",
    year: 2003,
    composer: "Ouseppachan",
    singer: "Santhosh Keshav & Vidhu Prathap",
    vibe: "melody",
  },
  {
    youtubeId: "fH-HT-UAYCI",
    title: "Karukare Karuthoru",
    titleMl: "കറുകറെ കറുത്തൊരു",
    movie: "Balettan",
    year: 2003,
    composer: "M. Jayachandran",
    singer: "Mohanlal",
    vibe: "mass",
  },
  {
    youtubeId: "XoSTsjKCGcI",
    title: "Ambalakkara Thechikavil",
    titleMl: "അമ്പലക്കര തെച്ചിക്കാവിൽ",
    movie: "Black",
    year: 2004,
    composer: "Alex Paul",
    singer: "M. G. Sreekumar",
    vibe: "mass",
  },
  {
    youtubeId: "2YKbSFmQh1Y",
    title: "Nillu Nillu Ente Neelakuyile",
    titleMl: "നില്ലു നില്ലു എന്റെ നീലക്കുയിലേ",
    movie: "Rain Rain Come Again",
    year: 2004,
    composer: "Jassie Gift",
    singer: "Jassie Gift",
    vibe: "mass",
  },
  {
    youtubeId: "-4Wl2fHHAVs",
    title: "Themma Themma",
    titleMl: "തെമ്മാ തെമ്മാ",
    movie: "Rain Rain Come Again",
    year: 2004,
    composer: "Jassie Gift",
    singer: "Jyotsna Radhakrishnan & Jassie Gift",
    vibe: "mass",
  },
  {
    youtubeId: "MCrtP7_wvcY",
    title: "Maamazhayile",
    titleMl: "മാമഴയിലേ",
    movie: "Mayilaattam",
    year: 2004,
    composer: "M. Jayachandran",
    singer: "Sujatha Mohan",
    vibe: "melody",
  },
  {
    youtubeId: "LlGajmW_qb8",
    title: "Maattupetti Koyilile",
    titleMl: "മാട്ടുപ്പെട്ടി കോയിലിലെ",
    movie: "Mayilaattam",
    year: 2004,
    composer: "M. Jayachandran",
    singer: "Afsal & Chithra Iyer",
    vibe: "nadan",
  },
  {
    youtubeId: "CHVNf3r2PJc",
    title: "Mehruba",
    titleMl: "മെഹ്‌റുബാ",
    movie: "Perumazhakkalam",
    year: 2004,
    composer: "M. Jayachandran",
    singer: "Afsal & Jyotsna",
    vibe: "mappila",
  },
  {
    youtubeId: "k_81OMJCmjQ",
    title: "Kuttanadan Kaayalile",
    titleMl: "കുട്ടനാടൻ കായലിലെ",
    movie: "Kaazhcha",
    year: 2004,
    composer: "Mohan Sithara",
    singer: "Kalabhavan Mani & Madhu Balakrishnan",
    vibe: "nadan",
  },
  /*
   * Bus Conductor, twice. A film about a man who spends his life on a private bus
   * has a fair claim to two entries on a playlist about what played on one.
   */
  {
    youtubeId: "aceDEQpRnZE",
    title: "Maanathe Manichithathe",
    titleMl: "മാനത്തെ മണിച്ചിത്തത്തേ",
    movie: "Bus Conductor",
    year: 2005,
    composer: "M. Jayachandran",
    singer: "Madhu Balakrishnan & Rimi Tomy",
    vibe: "mass",
  },
  {
    youtubeId: "j0zjwVeqn6c",
    title: "Etho Raathrimazha",
    titleMl: "ഏതോ രാത്രിമഴ",
    movie: "Bus Conductor",
    year: 2005,
    composer: "M. Jayachandran",
    singer: "K. J. Yesudas",
    vibe: "melody",
  },
  {
    youtubeId: "Ppo3oPo4NYw",
    title: "Velmuruka Harohara",
    titleMl: "വേൽമുരുകാ ഹരോഹര",
    movie: "Naran",
    year: 2005,
    composer: "Deepak Dev",
    singer: "M. G. Sreekumar",
    vibe: "mass",
  },
  {
    youtubeId: "mdsH0Nzsddk",
    title: "Dum Dum Dum Dooreyetho",
    titleMl: "ഡും ഡും ഡും ദൂരെയേതോ",
    movie: "Raakkilippaattu",
    year: 2007,
    composer: "Vidyasagar",
    singer: "K. S. Chithra & Sujatha Mohan",
    vibe: "melody",
  },
  {
    youtubeId: "XpoyMxq48y8",
    title: "Aarumukhan Munnil Chennu",
    titleMl: "ആറുമുഖൻ മുന്നിൽ ചെന്നു",
    movie: "Mulla",
    year: 2008,
    composer: "Vidyasagar",
    singer: "Rimi Tomy",
    vibe: "melody",
  },
  {
    youtubeId: "Vbma1brQX-Q",
    title: "Changazhi Muthumayi",
    titleMl: "ചങ്ങഴി മുത്തുമായി",
    movie: "Loudspeaker",
    year: 2009,
    composer: "Bijibal",
    singer: "Mammootty",
    vibe: "mass",
  },

  /* ── the 2010s: the last decade before the speaker went Bluetooth ─────── */
  {
    youtubeId: "IwysyMb26Zg",
    title: "Manikinavin Kothumbuvallam",
    titleMl: "മണിക്കിനാവിൻ കൊതുമ്പുവള്ളം",
    movie: "Pokkiri Raja",
    year: 2010,
    composer: "Jassie Gift",
    singer: "K. J. Yesudas & Sujatha Mohan",
    vibe: "melody",
  },
  {
    youtubeId: "sWT_V7XyDKs",
    title: "Ona Veyil Olangalil",
    titleMl: "ഓണവെയിൽ ഓളങ്ങളിൽ",
    movie: "Bombay March 12",
    year: 2011,
    composer: "Afzal Yusuff",
    singer: "M. G. Sreekumar",
    vibe: "melody",
  },
  {
    youtubeId: "cE1vnvXPJJ4",
    title: "Pathinezhinte Poonkaralil",
    titleMl: "പതിനേഴിന്റെ പൂങ്കരളിൽ",
    movie: "Vellaripravinte Changathi",
    year: 2011,
    composer: "Mohan Sithara",
    singer: "Kabeer & Shreya Ghoshal",
    vibe: "melody",
  },
  {
    youtubeId: "ZwXiooPGLjQ",
    title: "Kakka Malayile",
    titleMl: "കാക്ക മലയിലെ",
    movie: "Mallu Singh",
    year: 2012,
    composer: "M. Jayachandran",
    singer: "Alex",
    vibe: "mass",
  },
  {
    youtubeId: "ehj1UpZJSrA",
    title: "Ullasa Gaayike",
    titleMl: "ഉല്ലാസ ഗായികേ",
    movie: "Adi Kapyare Koottamani",
    year: 2015,
    composer: "Shaan Rahman",
    singer: "Vidhu Prathap",
    vibe: "mass",
  },
  {
    youtubeId: "VNg556FUOUs",
    title: "Arikil Pathiye",
    titleMl: "അരികിൽ പതിയേ",
    movie: "Oru Murai Vanthu Paarthaya",
    year: 2016,
    composer: "Vinu Thomas",
    singer: "Najeem Arshad",
    vibe: "melody",
  },
  {
    youtubeId: "bRYaCXVW7Hg",
    title: "Dooreyo",
    titleMl: "ദൂരെയോ",
    movie: "Aanandam",
    year: 2016,
    composer: "Sachin Warrier",
    singer: "Vishak Nair & Sachin Warrier",
    vibe: "melody",
  },
  {
    youtubeId: "bY_LdUERXjQ",
    title: "Neeyilla Neram",
    titleMl: "നീയില്ലാ നേരം",
    movie: "Luca",
    year: 2019,
    composer: "Sooraj S. Kurup",
    singer: "Sooraj S. Kurup & Deepa Palanad",
    vibe: "melody",
  },

  /*
   * ── മാപ്പിളപ്പാട്ട് albums, undated ──────────────────────────────────────
   *
   * Two album tracks the search turned up. No public source dates either record, so
   * they carry no year — half of Malabar can sing them and nobody can date them.
   */
  {
    youtubeId: "av8Di_5FYMA",
    title: "Paalnila Punchiri",
    titleMl: "പാൽനിലാ പുഞ്ചിരി",
    movie: "Midad",
    composer: "K. A. Latheef",
    singer: "K. G. Markose",
    vibe: "mappila",
  },
  {
    youtubeId: "XfqWftKayFY",
    title: "Laile Laile Swargapoo",
    titleMl: "ലൈലേ ലൈലേ സ്വർഗപ്പൂ",
    movie: "Kalbhanu Fathima",
    composer: "M. Kunji Moosa",
    singer: "Afsal",
    vibe: "mappila",
  },
];
