import type { Track } from "@/engine";

/**
 * The playlist. This file *is* the product — the engineering was the easy half.
 *
 * **Inclusion filter.** Not "good Malayalam song". It has to be a song that came
 * out of a blown speaker over a diesel engine, somewhere between two towns, loud
 * enough that the whole bus heard it whether or not it wanted to. That keeps most
 * of the classical-leaning canon out and lets in a lot that nobody would call
 * tasteful.
 *
 * **How it was built.** `npm run resolve-tracks` searched YouTube for every line
 * in `scripts/candidates.ts` and preferred the label and studio channels, then
 * read the film, year, composer and singer off each upload's own description.
 * That pass corrected several things memory had wrong — "Devadoothar Paadi" is
 * Kaathodu Kaathoram, not Aniyathipraavu; "Onnam Ragam Paadi" is
 * Thoovanathumbikal; Thenmavin Kombathu is Berny–Ignatius, not Vidyasagar;
 * "Thumbi Vaa" is Ilaiyaraaja. The Malayalam titles are typed by hand, taking the
 * official spelling from the upload title wherever it carried one.
 *
 * **Every ID points at a label, studio or artist upload wherever one exists**,
 * because those are the ones that stay up and stay embeddable. `npm run
 * check-tracks` proves each still resolves *and* still allows embedding.
 *
 * **Undated tracks are undated on purpose.** The nadan and mappila albums —
 * Kalabhavan Mani's records above all — have no release year any public source
 * agrees on, so they carry no `year` rather than a confident guess. Roughly
 * chronological otherwise, so the spread stays visible at a glance.
 *
 * To suggest a song: add it to `scripts/candidates.ts`, run the resolver, and
 * open a pull request against this file.
 */
export const tracks: readonly Track[] = [
  /* ── the 80s, which never stopped playing on these routes ─────────────── */
  {
    youtubeId: "UCt6mp5Nnx4",
    title: "Mizhiyoram Nananju",
    titleMl: "മിഴിയോരം നനഞ്ഞൊഴുകും",
    movie: "Manjil Virinja Pookkal",
    year: 1980,
    composer: "Jerry Amaldev",
    singer: "K. J. Yesudas",
    vibe: "melody",
  },
  {
    youtubeId: "WrRUrCwVoPQ",
    title: "Thumbi Vaa",
    titleMl: "തുമ്പീ വാ",
    movie: "Olangal",
    year: 1982,
    composer: "Ilaiyaraaja",
    singer: "S. Janaki",
    vibe: "melody",
  },
  {
    youtubeId: "HTNDApRIv-M",
    title: "Kasthoorimaan Kurunne",
    titleMl: "കസ്തൂരിമാൻ കുരുന്നേ",
    movie: "Kanamarayathu",
    year: 1984,
    composer: "Shyam",
    singer: "S. Janaki",
    vibe: "melody",
  },
  {
    youtubeId: "nKhh3aqNRWA",
    title: "Aayiram Kannumai",
    titleMl: "ആയിരം കണ്ണുമായ്",
    movie: "Nokkethadhoorathu Kannum Nattu",
    year: 1984,
    composer: "Jerry Amaldev",
    singer: "K. S. Chithra",
    vibe: "melody",
  },
  {
    youtubeId: "emF9R6LGb7A",
    title: "Anuragini Itha",
    titleMl: "അനുരാഗിണീ ഇതാ",
    movie: "Oru Kudakkeezhil",
    year: 1985,
    composer: "Johnson",
    singer: "K. J. Yesudas",
    vibe: "melody",
  },
  {
    youtubeId: "gzkBVmxxDY8",
    title: "Devadoothar Paadi",
    titleMl: "ദേവദൂതർ പാടി",
    movie: "Kaathodu Kaathoram",
    year: 1985,
    composer: "Ouseppachan",
    singer: "K. J. Yesudas",
    vibe: "melody",
  },
  {
    youtubeId: "YqEhznI1xak",
    title: "Koottil Ninnum",
    titleMl: "കൂട്ടിൽ നിന്നും",
    movie: "Thalavattam",
    year: 1986,
    composer: "Raghu Kumar",
    singer: "K. J. Yesudas",
    vibe: "melody",
  },
  {
    youtubeId: "iPa1C30GzWE",
    title: "Ilam Manjin Kulirumay",
    titleMl: "ഇളം മഞ്ഞിൻ കുളിരുമായ്",
    movie: "Ninnishtam Ennishtam",
    year: 1986,
    composer: "Kannur Rajan",
    singer: "K. J. Yesudas & S. Janaki",
    vibe: "melody",
  },
  {
    youtubeId: "IgcgMXFszyg",
    title: "Poonkaatte Poyi Chollamo",
    titleMl: "പൂങ്കാറ്റേ പോയി ചൊല്ലാമോ",
    movie: "Shyama",
    year: 1986,
    composer: "Raghukumar",
    singer: "Unni Menon & K. S. Chithra",
    vibe: "melody",
  },
  {
    youtubeId: "pBbHUxjiKd8",
    title: "Onnam Ragam Paadi",
    titleMl: "ഒന്നാം രാഗം പാടി",
    movie: "Thoovanathumbikal",
    year: 1987,
    composer: "Perumbavoor G. Raveendranath",
    singer: "G. Venugopal & K. S. Chithra",
    vibe: "melody",
  },

  /* ── the 90s: the decade the back seat took over ──────────────────────── */
  {
    youtubeId: "cWlT6deMZJ8",
    title: "Kilukil Pambaram",
    titleMl: "കിലുകിൽ പമ്പരം",
    movie: "Kilukkam",
    year: 1991,
    composer: "S. P. Venkatesh",
    singer: "M. G. Sreekumar",
    vibe: "mass",
  },
  {
    youtubeId: "G3UefvEW6JU",
    title: "Anthiveyil Ponnu Thirum",
    titleMl: "അന്തിവെയിൽ പൊന്നുതിരും",
    movie: "Ulladakkam",
    year: 1991,
    composer: "Ouseppachan",
    singer: "K. J. Yesudas & Sujatha Mohan",
    vibe: "melody",
  },
  {
    youtubeId: "PJsrByKopEU",
    title: "Ramakadha Ganalayam",
    titleMl: "രാമകഥാ ഗാനലയം",
    movie: "Bharatham",
    year: 1991,
    composer: "Raveendran",
    singer: "K. J. Yesudas",
    vibe: "melody",
  },
  {
    youtubeId: "gMtK5D5AWBg",
    title: "Padakali Chandi",
    titleMl: "പടകാളി ചണ്ഡി ചങ്കുരുത്തി",
    movie: "Yodha",
    year: 1992,
    composer: "A. R. Rahman",
    singer: "K. J. Yesudas & M. G. Sreekumar",
    vibe: "mass",
  },
  {
    youtubeId: "hk9FOM-_1YA",
    title: "Karutha Penne",
    titleMl: "കറുത്ത പെണ്ണേ",
    movie: "Thenmavin Kombathu",
    year: 1994,
    composer: "Berny–Ignatius",
    singer: "M. G. Sreekumar & K. S. Chithra",
    vibe: "mass",
  },
  {
    youtubeId: "EZI1nw1d55g",
    title: "Harimuraleeravam",
    titleMl: "ഹരിമുരളീരവം",
    movie: "Aaraam Thampuran",
    year: 1997,
    composer: "Raveendran",
    singer: "K. J. Yesudas",
    vibe: "melody",
  },
  {
    youtubeId: "bwzxaNKVjBQ",
    title: "Onnanam Kunninmel",
    titleMl: "ഒന്നാനാം കുന്നിന്മേൽ",
    movie: "Mayilppeelikkavu",
    year: 1998,
    composer: "Berny–Ignatius",
    singer: "K. J. Yesudas & K. S. Chithra",
    vibe: "nadan",
  },

  /* ── the 2000s: Ravanaprabhu on the tape deck, Mani on the next one ───── */
  {
    youtubeId: "6uEFZchRTqM",
    title: "Avvaa Havvaa",
    titleMl: "അവ്വാ ഹവ്വാ",
    movie: "Sathyam Sivam Sundaram",
    year: 2000,
    composer: "Vidyasagar",
    singer: "Mano & Swarnalatha",
    vibe: "mass",
  },
  {
    youtubeId: "2Iazv6UhA5g",
    title: "Thakilu Pukilu",
    titleMl: "തകിലു പുകിലു",
    movie: "Ravanaprabhu",
    year: 2001,
    composer: "Suresh Peters",
    singer: "M. G. Sreekumar & Sujatha Mohan",
    vibe: "mass",
  },
  {
    youtubeId: "NTqJeVhkaR4",
    title: "Pottukuthedi",
    titleMl: "പൊട്ടുകുത്തേടി",
    movie: "Ravanaprabhu",
    year: 2001,
    composer: "Suresh Peters",
    singer: "Sreeram & Swarnalatha",
    vibe: "mass",
  },
  {
    youtubeId: "HK8GDwrWHuU",
    title: "Varuthantoppam Olichuchadiya",
    titleMl: "വരുത്തന്റൊപ്പം ഒളിച്ചുചാടിയ",
    movie: "Aakashathile Paravakal",
    year: 2001,
    composer: "Sidhartha Vijayan",
    singer: "Kalabhavan Mani",
    vibe: "nadan",
  },
  {
    youtubeId: "Pg5SWsBgKnk",
    title: "Karuppinazhaku",
    titleMl: "കറുപ്പിനഴക്",
    movie: "Swapnakkoodu",
    year: 2003,
    composer: "Alex Paul",
    singer: "Rajesh Vijay, Pradeep Babu & Jyotsna",
    vibe: "mass",
  },
  {
    youtubeId: "pixeuHwj9t4",
    title: "Kasavinte Thattamittu",
    titleMl: "കസവിന്റെ തട്ടമിട്ട്",
    movie: "Kilichundan Mampazham",
    year: 2003,
    composer: "Vidyasagar",
    singer: "Vineeth Sreenivasan",
    vibe: "mappila",
  },
  {
    youtubeId: "L-kKWXZ5wwc",
    title: "Kuttanadan Kayalile",
    titleMl: "കുട്ടനാടൻ കായലിലെ",
    movie: "Kaazhcha",
    year: 2004,
    composer: "Mohan Sithara",
    singer: "Madhu Balakrishnan & Kalabhavan Mani",
    vibe: "nadan",
  },
  {
    youtubeId: "CHVNf3r2PJc",
    title: "Mehruba",
    titleMl: "മെഹ്‌റുബാ",
    movie: "Perumazhakkalam",
    year: 2004,
    composer: "M. Jayachandran",
    singer: "Afsal & Jyotsna",
    vibe: "mappila",
  },
  {
    youtubeId: "pmrUtMlzEFU",
    title: "Kando Kando",
    titleMl: "കണ്ടോ കണ്ടോ",
    movie: "Mahasamudram",
    year: 2006,
    composer: "M. Jayachandran",
    singer: "G. Venugopal & K. S. Chithra",
    vibe: "mass",
  },
  {
    youtubeId: "Y2df-yFAIR4",
    title: "Muthumazha",
    titleMl: "മുത്തുമഴ",
    movie: "Big B",
    year: 2007,
    composer: "Alphons Joseph",
    singer: "Vineeth Sreenivasan & Jyotsna",
    vibe: "melody",
  },

  /* ── the 2010s: the last decade before the speaker went Bluetooth ─────── */
  {
    youtubeId: "0ezn5lcbQmc",
    title: "Rab Rab Rab",
    titleMl: "റബ് റബ് റബ്",
    movie: "Mallu Singh",
    year: 2012,
    composer: "M. Jayachandran",
    singer: "Shankar Mahadevan",
    vibe: "mass",
  },
  {
    youtubeId: "ULy7ACGybOM",
    title: "Appangalembadum",
    titleMl: "അപ്പങ്ങളെമ്പാടും",
    movie: "Ustad Hotel",
    year: 2012,
    composer: "Gopi Sundar",
    singer: "Anna Katharina Valayil",
    vibe: "nadan",
  },
  {
    youtubeId: "Xq2GDrTNTXE",
    title: "Muthuchippi Poloru",
    titleMl: "മുത്തുച്ചിപ്പി പോലൊരു",
    movie: "Thattathin Marayathu",
    year: 2012,
    composer: "Shaan Rahman",
    singer: "Sachin Warrier & Ramya Nambeeshan",
    vibe: "melody",
  },
  {
    youtubeId: "X48wPny1hTw",
    title: "Anuraagathin Velayil",
    titleMl: "അനുരാഗത്തിൻ വേളയിൽ",
    movie: "Thattathin Marayathu",
    year: 2012,
    composer: "Shaan Rahman",
    singer: "Vineeth Sreenivasan",
    vibe: "melody",
  },
  {
    youtubeId: "SuuypjzzqRw",
    title: "Pista",
    titleMl: "പിസ്ത",
    movie: "Neram",
    year: 2013,
    composer: "Rajesh Murugesan",
    singer: "Shabareesh Varma",
    vibe: "mass",
  },
  {
    youtubeId: "r3fhuJJRcYc",
    title: "Vaathil Melle",
    titleMl: "വാതിൽ മെല്ലെ",
    movie: "Neram",
    year: 2013,
    composer: "Rajesh Murugesan",
    singer: "Sachin Warrier",
    vibe: "melody",
  },
  {
    youtubeId: "6nngUnGZ5sY",
    title: "Kanni Penne",
    titleMl: "കന്നിപ്പെണ്ണേ",
    movie: "Sound Thoma",
    year: 2013,
    composer: "Gopi Sundar",
    singer: "Shankar Mahadevan & Rimi Tomy",
    vibe: "mass",
  },
  {
    youtubeId: "Qs2ta9_CaKM",
    title: "Kaattu Mooliyo",
    titleMl: "കാറ്റ് മൂളിയോ",
    movie: "Ohm Shanthi Oshaana",
    year: 2014,
    composer: "Shaan Rahman",
    singer: "Vineeth Sreenivasan",
    vibe: "mass",
  },
  {
    youtubeId: "qHnd9Hls12w",
    title: "Aluva Puzhayude Theerathu",
    titleMl: "ആലുവാ പുഴയുടെ തീരത്ത്",
    movie: "Premam",
    year: 2015,
    composer: "Rajesh Murugesan",
    singer: "Vineeth Sreenivasan",
    vibe: "mass",
  },
  {
    youtubeId: "ewDnUX2x8Ro",
    title: "Malare",
    titleMl: "മലരേ",
    movie: "Premam",
    year: 2015,
    composer: "Rajesh Murugesan",
    singer: "Vijay Yesudas",
    vibe: "melody",
  },
  {
    youtubeId: "flISEBsDSH8",
    title: "Kaathirunnu Kaathirunnu",
    titleMl: "കാത്തിരുന്നു കാത്തിരുന്നു",
    movie: "Ennu Ninte Moideen",
    year: 2015,
    composer: "M. Jayachandran",
    singer: "Shreya Ghoshal",
    vibe: "melody",
  },
  {
    youtubeId: "bRYaCXVW7Hg",
    title: "Dooreyo",
    titleMl: "ദൂരെയോ",
    movie: "Aanandam",
    year: 2016,
    composer: "Sachin Warrier",
    singer: "Vishak Nair & Sachin Warrier",
    vibe: "melody",
  },
  {
    youtubeId: "VNg556FUOUs",
    title: "Arikil Pathiye",
    titleMl: "അരികിൽ പതിയേ",
    movie: "Oru Murai Vanthu Paarthaya",
    year: 2016,
    composer: "Vinu Thomas",
    singer: "Najeem Arshad",
    vibe: "melody",
  },
  {
    youtubeId: "FAn2i7gu32w",
    title: "Lailakame",
    titleMl: "ലൈലാകമേ",
    movie: "Ezra",
    year: 2017,
    composer: "Rahul Raj",
    singer: "Haricharan",
    vibe: "melody",
  },
  {
    youtubeId: "FXiaIH49oAU",
    title: "Entammede Jimikki Kammal",
    titleMl: "എന്റമ്മേടെ ജിമിക്കി കമ്മൽ",
    movie: "Velipadinte Pusthakam",
    year: 2017,
    composer: "Shaan Rahman",
    singer: "Vineeth Sreenivasan & Renjith Unni",
    vibe: "mass",
  },
  {
    youtubeId: "YRrbcn37rbE",
    title: "Jillam Jillala",
    titleMl: "ജില്ലം ജില്ലാല",
    movie: "Honey Bee 2",
    year: 2017,
    composer: "Deepak Dev",
    singer: "Afsal, Rimi Tomy & Anwar",
    vibe: "mass",
  },
  {
    youtubeId: "53Qn0CJ4ws8",
    title: "Vaanam Thilathilakkanu",
    titleMl: "വാനം തിളതിളക്കണ്",
    movie: "Comrade in America",
    year: 2017,
    composer: "Gopi Sundar",
    singer: "Dulquer Salmaan",
    vibe: "mass",
  },
  {
    youtubeId: "UsJkhu8K1gs",
    title: "Aaro Nenjil",
    titleMl: "ആരോ നെഞ്ചിൽ",
    movie: "Godha",
    year: 2017,
    composer: "Shaan Rahman",
    singer: "Gowry Lekshmi",
    vibe: "melody",
  },
  {
    youtubeId: "W0fKl43QmIE",
    title: "Manikya Malaraya Poovi",
    titleMl: "മാണിക്യ മലരായ പൂവി",
    movie: "Oru Adaar Love",
    year: 2018,
    composer: "Shaan Rahman",
    singer: "Vineeth Sreenivasan",
    vibe: "mappila",
  },
  {
    youtubeId: "vjKFXhucXIU",
    title: "Poomuthole",
    titleMl: "പൂമുത്തോളേ",
    movie: "Joseph",
    year: 2018,
    composer: "Ranjin Raj",
    singer: "Vijay Yesudas",
    vibe: "melody",
  },
  {
    youtubeId: "3y4OWH92Ic4",
    title: "Karineela Kannulla",
    titleMl: "കരിനീല കണ്ണുള്ള",
    movie: "Joseph",
    year: 2018,
    composer: "Ranjin Raj",
    singer: "Karthik & Akhila Anand",
    vibe: "melody",
  },
  {
    youtubeId: "DInfmi-YIiw",
    title: "Jeevamshamayi",
    titleMl: "ജീവാംശമായ്",
    movie: "Theevandi",
    year: 2018,
    composer: "Kailas Menon",
    singer: "Shreya Ghoshal & Harisankar K. S.",
    vibe: "melody",
  },
  {
    youtubeId: "P-jKtzUuVcM",
    title: "Pavizha Mazha",
    titleMl: "പവിഴമഴ",
    movie: "Athiran",
    year: 2019,
    composer: "P. S. Jayhari",
    singer: "K. S. Harisankar",
    vibe: "melody",
  },
  {
    youtubeId: "P7-xs4XF4CA",
    title: "Kudukku",
    titleMl: "കുടുക്ക്",
    movie: "Love Action Drama",
    year: 2019,
    composer: "Shaan Rahman",
    singer: "Vineeth Sreenivasan",
    vibe: "mass",
  },

  /*
   * ── നാടൻ പാട്ട് and മാപ്പിളപ്പാട്ട്, undated ───────────────────────────
   *
   * Kalabhavan Mani's folk records are the other half of what actually played on
   * these buses, and none of them has a release year anybody agrees on — so they
   * carry none. Half of Kerala can sing these and nobody can date them.
   */
  {
    youtubeId: "tRaJPNNjK6M",
    title: "Chalakkudikkaran Changathi",
    titleMl: "ചാലക്കുടിക്കാരൻ ചങ്ങാതി",
    movie: "Nadan Pattukal",
    composer: "Kalabhavan Mani",
    singer: "Kalabhavan Mani",
    vibe: "nadan",
  },
  {
    youtubeId: "YYZWi3OQqWw",
    title: "Odapazham Poloru Pennu",
    titleMl: "ഓടപ്പഴം പോലൊരു പെണ്ണ്",
    movie: "Nadan Pattukal",
    composer: "Kalabhavan Mani",
    singer: "Kalabhavan Mani",
    vibe: "nadan",
  },
  {
    youtubeId: "cFlQDxVvIHY",
    title: "Maari Poomari",
    titleMl: "മാരി പൂമാരി",
    movie: "Nadan Pattukal",
    composer: "Kalabhavan Mani",
    singer: "Kalabhavan Mani",
    vibe: "nadan",
  },
  {
    youtubeId: "0QSr9S73gtU",
    title: "Njan Kudikkana Kanjeelenthinu",
    titleMl: "ഞാൻ കുടിക്കണ കഞ്ഞീലെന്തിന്",
    movie: "Nadan Pattukal",
    composer: "Kalabhavan Mani",
    singer: "Kalabhavan Mani",
    vibe: "nadan",
  },
  {
    youtubeId: "GSaLsSTd-WU",
    title: "Kunjunnaalil",
    titleMl: "കുഞ്ഞുന്നാളിൽ",
    movie: "Nadan Pattukal",
    composer: "Kalabhavan Mani",
    singer: "Kalabhavan Mani",
    vibe: "nadan",
  },
  {
    youtubeId: "D5bqlweWjCs",
    title: "Engupoyi En Seethe",
    titleMl: "എങ്ങുപോയി എൻ സീതേ",
    movie: "Padan Kothicha Paattukal",
    composer: "Arumughan Venkidangu",
    singer: "Kalabhavan Mani",
    vibe: "nadan",
  },
  {
    youtubeId: "4iCJHcUCeMI",
    title: "Balettan Molalledi",
    titleMl: "ബാലേട്ടൻ മോളല്ലേടി",
    movie: "Kattile Kaatana",
    composer: "Kalabhavan Mani",
    singer: "Kalabhavan Mani",
    vibe: "nadan",
  },
  {
    youtubeId: "dDEtJrvYZpI",
    title: "Kanniprasavam",
    titleMl: "കന്നിപ്രസവം",
    movie: "Mappilappattukal",
    composer: "Kalabhavan Mani",
    singer: "Kalabhavan Mani",
    vibe: "mappila",
  },
  {
    youtubeId: "y9yQ-kxIGOU",
    title: "Kadakkanninmunakonden",
    titleMl: "കടക്കണ്ണിൻമുനകൊണ്ടെൻ",
    movie: "Mappilappattukal",
    composer: "Kalabhavan Mani",
    singer: "Kalabhavan Mani",
    vibe: "mappila",
  },
  {
    youtubeId: "M1_VFAFP2WM",
    title: "Kuttanadan Punchayile",
    titleMl: "കുട്ടനാടൻ പുഞ്ചയിലെ",
    movie: "Kaavalam Chundan",
    composer: "Traditional",
    singer: "K. J. Yesudas",
    vibe: "nadan",
  },
  {
    youtubeId: "vrQzJJ3tI7k",
    title: "Ambalappuzhe Unnikkannanodu",
    titleMl: "അമ്പലപ്പുഴെ ഉണ്ണിക്കണ്ണനോട്",
    movie: "Adhwaytham",
    composer: "M. G. Radhakrishnan",
    singer: "M. G. Sreekumar & K. S. Chithra",
    vibe: "nadan",
  },
  {
    youtubeId: "n-cmMyJ--M8",
    title: "Palnila Punchiri",
    titleMl: "പാൽനിലാ പുഞ്ചിരി",
    movie: "Midad",
    composer: "K. A. Latheef",
    singer: "Dana Razik",
    vibe: "mappila",
  },
];
